package com.antiaginglabs.companion

import android.content.Context
import androidx.health.connect.client.HealthConnectClient
import androidx.health.connect.client.permission.HealthPermission
import androidx.health.connect.client.records.*
import androidx.health.connect.client.request.ChangesTokenRequest
import androidx.health.connect.client.changes.*
import kotlinx.serialization.json.*
import java.time.Instant
import java.time.ZoneId

class HealthConnectSyncManager(private val context:Context){private val client=HealthConnectClient.getOrCreate(context);private val prefs=context.getSharedPreferences("health-cursors",0);private val recordTypes=setOf(StepsRecord::class,RestingHeartRateRecord::class,HeartRateVariabilityRmssdRecord::class,SleepSessionRecord::class,ActiveCaloriesBurnedRecord::class,ExerciseSessionRecord::class,Vo2MaxRecord::class);val permissions=recordTypes.map{HealthPermission.getReadPermission(it)}.toSet();init{CompanionAPI.installContext(context)}
  suspend fun syncAll():String{CompanionAPI.installContext(context);var sent=0;for(type in recordTypes){sent+=syncType(type.java.name)};return if(sent==0)"Up to date" else "Synced $sent changes"}
  private suspend fun syncType(typeName:String):Int{val tokenKey="token:$typeName";var token=prefs.getString(tokenKey,null);if(token==null){token=client.getChangesToken(ChangesTokenRequest(recordTypes=recordTypes.filter{it.java.name==typeName}.toSet()))};val samples=buildJsonArray{var more:Boolean;do{val changes=client.getChanges(token!!);for(change in changes.changes){when(change){is UpsertionChange->{add(toSample(change.record));};is DeletionChange->add(buildJsonObject{put("externalId",change.recordId);put("typeCode",canonicalType(typeName));put("startAt",Instant.now().toString());put("endAt",Instant.now().toString());put("timezone",ZoneId.systemDefault().id);put("sourceName","Health Connect");put("sourceBundle","android.health.connect");put("deleted",true)})}};token=changes.nextChangesToken;more=changes.hasMore}while(more)};if(samples.isNotEmpty())CompanionAPI.sync(context,token,samples);prefs.edit().putString(tokenKey,token).apply();return samples.size}
  private fun canonicalType(name:String)=when{ name.contains("StepsRecord")->"steps";name.contains("RestingHeartRate")->"resting_heart_rate";name.contains("HeartRateVariabilityRmssd")->"heart_rate_variability_rmssd";name.contains("SleepSession")->"sleep_session";name.contains("ActiveCalories")->"active_energy";name.contains("ExerciseSession")->"workout";name.contains("Vo2Max")->"vo2_max";else->"unknown" }
  private fun toSample(record:Record):JsonObject{val (start,end,value,unit)=when(record){is StepsRecord->listOf(record.startTime,record.endTime,record.count.toDouble(),"count");is RestingHeartRateRecord->listOf(record.time,record.time,record.beatsPerMinute.toDouble(),"bpm");is HeartRateVariabilityRmssdRecord->listOf(record.time,record.time,record.heartRateVariabilityMillis,"ms");is SleepSessionRecord->listOf(record.startTime,record.endTime,null,null);is ActiveCaloriesBurnedRecord->listOf(record.startTime,record.endTime,record.energy.inKilocalories,"kcal");is ExerciseSessionRecord->listOf(record.startTime,record.endTime,null,null);is Vo2MaxRecord->listOf(record.time,record.time,record.vo2MillilitersPerMinuteKilogram,"mL/kg/min");else->listOf(Instant.now(),Instant.now(),null,null)};return buildJsonObject{put("externalId",record.metadata.id);put("typeCode",canonicalType(record::class.java.name));if(value is Double)put("value",value);if(unit is String)put("unit",unit);put("startAt",start.toString());put("endAt",end.toString());put("timezone",ZoneId.systemDefault().id);put("sourceName",record.metadata.dataOrigin.packageName);put("sourceBundle",record.metadata.dataOrigin.packageName);put("device",buildJsonObject{put("manufacturer",record.metadata.device?.manufacturer?:"");put("model",record.metadata.device?.model?:"")});put("metadata",buildJsonObject{put("lastModifiedTime",record.metadata.lastModifiedTime.toString())});put("deleted",false)}}
}
