"use client";
/* eslint-disable react-hooks/exhaustive-deps */
import { useMemo, useState } from "react";
import { useAppData } from "./app-provider";
import { UploadExperience } from "./workflow-experiences";

type Qc = { status?: string; callRate?: number; totalRecords?: number; calledRecords?: number; noCalls?: number; supportedCalls?: number; warnings?: string[] };
type Phenotype = { status?: "expressed" | "not_expressed" | "unknown"; label?: string; basis?: string; observedAt?: string | null };
type Reanalysis = { policyVersion?: string; lastAnalysedAt?: string | null; note?: string };
type Interpretation = Record<string, unknown> & { id?: string; gene?: string; rsid?: string; category?: string; title?: string; summary?: string; evidenceLevel?: string; evidenceLabel?: string; evidenceReleaseIdsJson?: string[]; limitationsJson?: string[]; limitations?: string[]; status?: string; hypothesis?: string; whatThisChanges?: string; wouldClarify?: string[]; phenotype?: Phenotype; actionPolicy?: string; canCreateAction?: boolean; reanalysis?: Reanalysis };

const phenotypeText = (status?: string) => status === "expressed" ? "Phenotype expressed" : status === "not_expressed" ? "Phenotype not expressed" : "Phenotype unknown";
const policyTone = (item: Interpretation) => item.status === "released" ? "sage" : "amber";

export function GeneticsExperience() {
  const { data, refresh } = useAppData();
  const artifacts = data?.genomics?.artifacts ?? [];
  const interpretations = (data?.genomics?.interpretations ?? []) as Interpretation[];
  const runs = data?.genomics?.runs ?? [];
  const [view, setView] = useState<"overview" | "variants" | "provenance">("overview");
  const [busy, setBusy] = useState("");
  const artifact = artifacts[0];
  const qc = (artifact?.qcJson ?? {}) as Qc;
  const grouped = useMemo(() => Object.entries(interpretations.reduce<Record<string, Interpretation[]>>((acc, item) => { const gene = String(item.gene); (acc[gene] ??= []).push(item); return acc; }, {})), [interpretations]);
  const released = interpretations.filter((item) => item.status === "released");
  const expressed = interpretations.filter((item) => item.phenotype?.status === "expressed").length;
  const unresolved = interpretations.filter((item) => item.phenotype?.status === "unknown").length;
  const policyVersion = interpretations.find((item) => item.reanalysis?.policyVersion)?.reanalysis?.policyVersion ?? "genetics policy pending";
  const reanalyse = async () => { if (!artifact) return; setBusy("reanalyse"); try { await fetch(`/api/genomics/${artifact.id}/reanalyse`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); await refresh(); } finally { setBusy(""); } };
  const generate = async () => { setBusy("report"); try { await fetch("/api/reports/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "genetics" }) }); await refresh(); } finally { setBusy(""); } };

  if (!artifact) return <><section className="genetics-empty paper-card"><div className="dna-orbit" aria-hidden="true"><i/><i/><i/><i/><i/><i/><span/></div><div><span className="card-kicker">INHERITED CONTEXT</span><h2>Add your raw genetics export</h2><p>DNA gives the Twin a lifelong inherited-context layer and better hypotheses. It never diagnoses a phenotype or creates an action without corroborating measurements, safety context, and review.</p><strong>Supported now: 23andMe-style text, MyHeritage-style CSV, VCF and gVCF.</strong></div></section><UploadExperience/></>;

  return <>
    <section className="genetics-hero">
      <div className="genetics-copy"><span className="card-kicker">INHERITED CONTEXT LAYER</span><h2>DNA helps decide what to investigate—not what to prescribe.</h2><p>Each supported finding becomes a testable hypothesis. The app keeps genotype, related phenotype, evidence, limitations, review state, and observed response separate.</p><div className="genetics-stat-row"><span><strong>{String(artifact.genomeBuild ?? "Unknown")}</strong><small>genome build</small></span><span><strong>{Math.round(Number(qc.callRate ?? 0) * 100)}%</strong><small>call rate</small></span><span><strong>{released.length}</strong><small>reviewed findings</small></span><span><strong>{unresolved}</strong><small>phenotypes unknown</small></span></div></div>
      <div className="genome-visual" aria-label="Genomic inherited-context map"><div className="genome-scan"/><div className="chromosome-track left">{Array.from({ length: 9 }, (_, i) => <i key={i}/>)}</div><div className="helix-core">{Array.from({ length: 12 }, (_, i) => <span style={{ "--i": i } as React.CSSProperties} key={i}><b/><em/></span>)}</div><div className="chromosome-track right">{Array.from({ length: 9 }, (_, i) => <i key={i}/>)}</div><strong>{String(artifact.format).replaceAll("_", " ")}</strong><small>{String(artifact.pipelineVersion)}</small></div>
    </section>

    <section className="genetics-toolbar"><div className="segmented-control"><button className={view === "overview" ? "active" : ""} onClick={() => setView("overview")}>Overview</button><button className={view === "variants" ? "active" : ""} onClick={() => setView("variants")}>Inherited findings</button><button className={view === "provenance" ? "active" : ""} onClick={() => setView("provenance")}>Evidence & reanalysis</button></div>{data?.roles.includes("admin") ? <div><button className="quiet-button" disabled={Boolean(busy)} onClick={() => void reanalyse()}>{busy === "reanalyse" ? "Running…" : "Run reanalysis"}</button><button className="primary-button" disabled={Boolean(busy)} onClick={() => void generate()}><span>{busy === "report" ? "Drafting…" : "Create genetics report"}</span><span>→</span></button></div> : null}</section>

    {view === "overview" ? <>
      <section className="genetics-overview">
        <article className="paper-card qc-card"><div className="section-head compact"><div><span className="card-kicker">QUALITY CONTROL</span><h2>{qc.status === "pass" ? "Usable file; interpretation remains governed" : "Review before interpretation"}</h2></div><span className={`status-pill ${qc.status === "pass" ? "sage" : "amber"}`}>{String(qc.status ?? artifact.status)}</span></div><div className="qc-meter"><i style={{ width: `${Math.round(Number(qc.callRate ?? 0) * 100)}%` }}/><span>Called {Number(qc.calledRecords ?? 0).toLocaleString("en-IN")} of {Number(qc.totalRecords ?? 0).toLocaleString("en-IN")} records</span></div><div className="qc-grid"><span><strong>{Number(qc.noCalls ?? 0).toLocaleString("en-IN")}</strong><small>no-calls</small></span><span><strong>{String(artifact.genomeBuild ?? "Unknown")}</strong><small>declared build</small></span><span><strong>{String(qc.supportedCalls ?? interpretations.length)}</strong><small>supported calls—not genome coverage</small></span></div>{(qc.warnings ?? []).map((warning) => <p className="qc-warning" key={warning}>◇ {warning}</p>)}</article>
        <article className="paper-card interpretation-summary"><span className="card-kicker">POLICY BOUNDARIES</span><h2>{interpretations.length} hypotheses · zero DNA-only actions</h2><p>Research-only and context-only variants cannot directly create protocol, supplement, diet, or training actions. Reviewer release makes a finding visible to the Twin; phenotype and response data determine whether it matters personally.</p><div><span><strong>{released.length}</strong><small>reviewed and available as context</small></span><span><strong>{expressed}</strong><small>related phenotypes currently expressed</small></span><span><strong>{unresolved}</strong><small>need corroborating phenotype data</small></span></div></article>
      </section>
      <section className="paper-card fusion-stack"><div className="section-head compact"><div><span className="card-kicker">HOW DNA EARNS INFLUENCE</span><h2>From inherited signal to personal learning</h2></div></div><div className="fusion-layers"><article className="available"><span>01</span><div><strong>Inherited finding</strong><small>QC + evidence + reviewer state</small><p>A supported call creates a bounded hypothesis, never an instruction.</p></div><i/></article><article className="pending"><span>02</span><div><strong>Phenotype check</strong><small>expressed · not expressed · unknown</small><p>Labs, wearables, intake, and family context test whether the related biology is currently visible.</p></div><i/></article><article className="pending"><span>03</span><div><strong>Measured response</strong><small>intervention + adherence + outcome</small><p>Only observed response can teach the Twin whether the hypothesis is personally useful.</p></div><i/></article></div></section>
      <section className="domain-mosaic">{grouped.slice(0, 6).map(([gene, items]) => <button type="button" className="domain-card paper-card" onClick={() => setView("variants")} key={gene}><div className="domain-card-top"><span className="gene-badge">{gene}</span><span className={`status-pill ${items.some((item) => item.status === "released") ? "sage" : "amber"}`}>{items.some((item) => item.status === "released") ? "reviewed" : "pending"}</span></div><h3>{items[0].title}</h3><div className="domain-metric"><strong>{phenotypeText(items[0].phenotype?.status)}</strong><span>{String(items[0].evidenceLabel ?? items[0].evidenceLevel ?? "context only")}</span></div><span>See hypothesis and limitations →</span></button>)}</section>
    </> : null}

    {view === "variants" ? <section className="variant-grid">{interpretations.map((item) => { const limitations = [...((item.limitationsJson as string[]) ?? []), ...((item.limitations as string[]) ?? [])]; return <article className="paper-card variant-card" key={String(item.id)}><div><span className="gene-badge">{String(item.gene)}</span><span className={`status-pill ${policyTone(item)}`}>{item.status === "released" ? "reviewed context" : "review pending"}</span></div><span className="card-kicker">{String(item.rsid)} · {String(item.category).replaceAll("_", " ")}</span><h3>{String(item.title)}</h3><p>{String(item.summary)}</p><div className="focus-status"><span>{phenotypeText(item.phenotype?.status)}</span><strong>{String(item.evidenceLabel ?? item.evidenceLevel ?? "context only")}</strong></div><p>{item.phenotype?.basis ?? "A related phenotype has not been established from current data."}</p><div className="evidence-box"><span>HYPOTHESIS</span><strong>{String(item.hypothesis ?? "Use only as inherited context alongside measured biology.")}</strong><p><strong>What this changes:</strong> {String(item.whatThisChanges ?? "No direct action; this finding stays contextual.")}</p><p><strong>What would clarify it:</strong> {((item.wouldClarify as string[]) ?? []).join(", ") || "corroborating phenotype and response data"}</p></div><strong>Action policy: DNA-only actions blocked</strong><details><summary>Evidence, limitations, and reanalysis</summary><ul>{Array.from(new Set(limitations)).map((limit) => <li key={limit}>{limit}</li>)}</ul><small>Evidence releases: {((item.evidenceReleaseIdsJson as string[]) ?? []).join(" · ") || "not released"}</small><small>Policy: {item.reanalysis?.policyVersion ?? policyVersion}</small><p>{item.reanalysis?.note ?? "Interpretation is rerun when the curated evidence policy changes; raw calls remain unchanged."}</p></details></article>; })}</section> : null}

    {view === "provenance" ? <section className="paper-card provenance-panel"><div className="section-head compact"><div><span className="card-kicker">REPRODUCIBLE EVIDENCE HISTORY</span><h2>Artifact, policy, and reanalysis lineage</h2></div><span className="eta-chip">{policyVersion}</span></div><div className="artifact-fingerprint"><span>SHA-256</span><code>{String(artifact.checksumSha256)}</code></div><p>Reanalysis updates interpretation against a pinned policy and evidence release. It does not change the raw file, silently upgrade a research association, or turn context-only evidence into an action.</p><div className="reanalysis-timeline">{runs.length ? runs.map((run, index) => <article key={String(run.id)}><i/><div><strong>Run {runs.length - index} · {String(run.trigger)}</strong><small>{new Date(String(run.createdAt)).toLocaleString()} · {String(run.pipelineVersion)}</small><p>{String((run.summaryJson as { interpreted?: number })?.interpreted ?? 0)} interpretations · evidence {((run.evidenceSetJson as string[]) ?? []).join(", ")}</p></div></article>) : <article><i/><div><strong>No completed reanalysis yet</strong><p>The first governed run will appear here after ingestion and review.</p></div></article>}</div></section> : null}
    <UploadExperience/>
  </>;
}
