"use client";
import { useEffect, useState } from "react";
import { useAppData } from "./app-provider";

export function ReportsExperience() {
  const { data, refresh } = useAppData(); const reports = data?.reports ?? []; const [selectedId, setSelectedId] = useState<string | null>(null); const [view, setView] = useState<"overview"|"deep">("overview"); const [busy, setBusy] = useState(false); const [details,setDetails]=useState<Record<string,Record<string,unknown>>>({}); const selected = reports.find((report) => report.id === selectedId) ?? reports[0]; const selectedKey=selected?String(selected.id):""; const detail=selectedKey?details[selectedKey]:undefined;
  useEffect(()=>{if(!selectedKey||details[selectedKey])return;let live=true;void fetch(`/api/reports/${selectedKey}`,{cache:"no-store"}).then(async(response)=>response.ok?await response.json() as Record<string,unknown>:null).then(result=>{if(live&&result)setDetails(current=>({...current,[selectedKey]:{...result,deepDiveJson:result.deep_dive_json}}));}).catch(()=>undefined);return()=>{live=false;};},[selectedKey,details]);
  const generate = async (type: string) => { setBusy(true); await fetch("/api/reports/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type }) }); await refresh(); setBusy(false); };
  const approve = async (id: string) => { setBusy(true); await fetch(`/api/reports/${id}/approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); await refresh(); setBusy(false); };
  return <><section className="report-grid">{reports.map((report) => <button onClick={() => {setSelectedId(String(report.id));setView("overview");}} className={`report-card paper-card ${selected?.id === report.id ? "selected" : ""}`} type="button" key={String(report.id)}><div className="report-card-top"><span className="report-glyph rust">{String(report.type).charAt(0).toUpperCase()}</span><span className="status-pill sage">{String(report.status)}</span></div><span className="card-kicker">{String(report.type)}</span><h3>{String(report.title)}</h3><p>{String(report.overview)}</p><div className="report-card-foot"><time>{String(report.sourceDate ?? "Current")}</time><span>Open →</span></div></button>)}</section>{selected ? <section className="paper-card report-reader"><div className="section-head"><div><span className="card-kicker">VERSIONED REPORT</span><h2>{String(selected.title)}</h2></div><div className="segmented-control"><button className={view === "overview" ? "active" : ""} onClick={() => setView("overview")} type="button">Overview</button><button className={view === "deep" ? "active" : ""} onClick={() => setView("deep")} type="button">Deep dive</button></div></div>{!detail?<div className="report-detail-loading" role="status">Loading report details…</div>:view === "overview" ? <div className="report-overview"><p>{String(selected.overview)}</p><div className="priority-panels">{((detail.deepDiveJson as { overview?: { priorities?: Array<{ domain: string; state: string; metric: string; target: string; confidence: number|string }> } })?.overview?.priorities ?? []).map((priority) => <article key={`${priority.domain}-${priority.metric}`}><span>{priority.state}</span><h3>{priority.domain}</h3><strong>{priority.metric}</strong><small>Target: {priority.target} · {typeof priority.confidence==="number"?`${Math.round(priority.confidence*100)}% confidence`:String(priority.confidence)}</small></article>)}</div></div> : <DeepReport value={detail.deepDiveJson as Record<string,unknown>}/>} {selected.status === "draft" && data?.roles.includes("admin") ? <button disabled={busy} onClick={() => void approve(String(selected.id))} className="primary-button" type="button"><span>Approve & publish</span><span>→</span></button> : null}</section> : null}{data?.roles.includes("admin") ? <section className="report-actions paper-card"><div><span className="card-kicker">REPORT STUDIO</span><h2>Generate from the latest verified state</h2></div><button disabled={busy} onClick={() => void generate("biomarkers")} type="button">Biomarker draft</button><button disabled={busy} onClick={() => void generate("wearables")} type="button">Wearable draft</button><button disabled={busy} onClick={() => void generate("genetics")} type="button">Genetics draft</button><button disabled={busy} onClick={() => void generate("twin")} type="button">Twin draft</button></section> : null}</>;
}

function DeepReport({value}:{value:Record<string,unknown>}){const genetics=value.genetics as {artifacts?:Array<Record<string,unknown>>;interpretations?:Array<Record<string,unknown>>}|undefined;const domains=(value.domains??[]) as Array<Record<string,unknown>>;const cross=(value.crossModal??[]) as Array<Record<string,unknown>>;const assistant=value.assistantDraft as {model?:string;status?:string;output?:{summary?:string;limitations?:string[]}}|undefined;return <div className="structured-deep-report">{assistant?<section className="assistant-draft-panel"><span className="card-kicker">ASSISTED DRAFT · {assistant.model}</span><p>{assistant.output?.summary}</p><small>{assistant.status} · reviewer approval required before publication</small></section>:null}{genetics?<><section><span className="card-kicker">ARTIFACT QUALITY</span><div className="deep-artifacts">{(genetics.artifacts??[]).map((artifact)=><article key={String(artifact.id)}><strong>{String(artifact.format)} · {String(artifact.genomeBuild)}</strong><small>{String(artifact.status)} · pipeline {String(artifact.pipelineVersion)}</small><code>{String(artifact.checksumSha256)}</code></article>)}</div></section><section><span className="card-kicker">SUPPORTED INTERPRETATIONS</span><div className="deep-findings">{(genetics.interpretations??[]).map((item)=><article key={String(item.id)}><span>{String(item.gene)} · {String(item.rsid)}</span><h3>{String(item.title)}</h3><p>{String(item.summary)}</p><small>{String(item.evidenceLevel)} · {String(item.reviewState)}</small></article>)}</div></section></>:null}{domains.length?<section><span className="card-kicker">DOMAIN STATES</span><div className="deep-findings">{domains.map((domain)=><article key={String(domain.code)}><span>{String(domain.status)} · {Math.round(Number(domain.confidence)*100)}% confidence</span><h3>{String(domain.label)}</h3><p>{String(domain.state)} · {String(domain.metric)} {String(domain.value)} {String(domain.unit??"")}</p><small>Target {String(domain.target)} · trend {String(domain.trend)}</small></article>)}</div></section>:null}{cross.length?<section><span className="card-kicker">CROSS-MODAL FINDINGS</span><div className="deep-findings">{cross.map((finding)=><article key={String(finding.id)}><span>{String(finding.domain)} · {Math.round(Number(finding.confidence)*100)}% confidence</span><h3>{String(finding.title)}</h3><p>{String(finding.statement)}</p><small>{String(finding.methodVersion)}</small></article>)}</div></section>:null}</div>}
