"use client";
import { useState } from "react";
import { useAppData } from "./app-provider";

export function ReportsExperience() {
  const { data, refresh } = useAppData(); const reports = data?.reports ?? []; const [selectedId, setSelectedId] = useState<string | null>(null); const [view, setView] = useState<"overview"|"deep">("overview"); const [busy, setBusy] = useState(false); const selected = reports.find((report) => report.id === selectedId) ?? reports[0];
  const generate = async (type: string) => { setBusy(true); await fetch("/api/reports/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type }) }); await refresh(); setBusy(false); };
  const approve = async (id: string) => { setBusy(true); await fetch(`/api/reports/${id}/approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); await refresh(); setBusy(false); };
  return <><section className="report-grid">{reports.map((report) => <button onClick={() => setSelectedId(String(report.id))} className={`report-card paper-card ${selected?.id === report.id ? "selected" : ""}`} type="button" key={String(report.id)}><div className="report-card-top"><span className="report-glyph rust">{String(report.type).charAt(0).toUpperCase()}</span><span className="status-pill sage">{String(report.status)}</span></div><span className="card-kicker">{String(report.type)}</span><h3>{String(report.title)}</h3><p>{String(report.overview)}</p><div className="report-card-foot"><time>{String(report.sourceDate ?? "Current")}</time><span>Open →</span></div></button>)}</section>{selected ? <section className="paper-card report-reader"><div className="section-head"><div><span className="card-kicker">VERSIONED REPORT</span><h2>{String(selected.title)}</h2></div><div className="segmented-control"><button className={view === "overview" ? "active" : ""} onClick={() => setView("overview")} type="button">Overview</button><button className={view === "deep" ? "active" : ""} onClick={() => setView("deep")} type="button">Deep dive</button></div></div>{view === "overview" ? <div className="report-overview"><p>{String(selected.overview)}</p><div className="priority-panels">{((selected.deepDiveJson as { overview?: { priorities?: Array<{ domain: string; state: string; metric: string; target: string; confidence: number }> } })?.overview?.priorities ?? []).map((priority) => <article key={priority.domain}><span>{priority.state}</span><h3>{priority.domain}</h3><strong>{priority.metric}</strong><small>Target: {priority.target} · {Math.round(priority.confidence*100)}% confidence</small></article>)}</div></div> : <pre className="deep-report">{JSON.stringify(selected.deepDiveJson, null, 2)}</pre>}{selected.status === "draft" && data?.roles.includes("admin") ? <button disabled={busy} onClick={() => void approve(String(selected.id))} className="primary-button" type="button"><span>Approve & publish</span><span>→</span></button> : null}</section> : null}{data?.roles.includes("admin") ? <section className="report-actions paper-card"><div><span className="card-kicker">REPORT STUDIO</span><h2>Generate from the latest verified state</h2></div><button disabled={busy} onClick={() => void generate("biomarkers")} type="button">Biomarker draft</button><button disabled={busy} onClick={() => void generate("wearables")} type="button">Wearable draft</button><button disabled={busy} onClick={() => void generate("twin")} type="button">Twin draft</button></section> : null}</>;
}
