"use client";

import { FormEvent, useEffect, useState } from "react";

type Ticket = { id: string; category: string; urgency: string; subject: string; status: string; created_at: string };
type RightsRequest = { id: string; request_type: string; status: string; created_at: string };

export function SupportExperience() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [requests, setRequests] = useState<RightsRequest[]>([]); const [consent, setConsent] = useState<boolean | null>(null); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => {
    const [ticketResponse, requestResponse, consentResponse] = await Promise.all([fetch("/api/support", { cache: "no-store" }), fetch("/api/privacy/requests", { cache: "no-store" }), fetch("/api/privacy/consent", { cache: "no-store" })]);
    if (ticketResponse.ok) setTickets(await ticketResponse.json() as Ticket[]); if (requestResponse.ok) setRequests(await requestResponse.json() as RightsRequest[]); if (consentResponse.ok) { const data = await consentResponse.json() as { granted?: boolean }; setConsent(Boolean(data.granted)); }
  };
  useEffect(() => { let live = true; void Promise.all([fetch("/api/support", { cache: "no-store" }), fetch("/api/privacy/requests", { cache: "no-store" }), fetch("/api/privacy/consent", { cache: "no-store" })]).then(async ([ticketResponse, requestResponse, consentResponse]) => { const nextTickets = ticketResponse.ok ? await ticketResponse.json() as Ticket[] : []; const nextRequests = requestResponse.ok ? await requestResponse.json() as RightsRequest[] : []; const nextConsent = consentResponse.ok ? Boolean((await consentResponse.json() as { granted?: boolean }).granted) : false; if (live) { setTickets(nextTickets); setRequests(nextRequests); setConsent(nextConsent); } }).catch(() => undefined); return () => { live = false; }; }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setNotice(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form.entries())) }); const result = await response.json() as { error?: string }; setNotice(response.ok ? "Your request is in the support queue." : result.error ?? "Could not send your request."); if (response.ok) { event.currentTarget.reset(); await load(); } setSaving(false); };
  const requestRight = async (requestType: "export" | "delete") => { setNotice(""); const response = await fetch("/api/privacy/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestType }) }); setNotice(response.ok ? `${requestType === "export" ? "Data-copy" : "Deletion"} request received. We will verify it before completing it.` : "Could not create this request."); if (response.ok) await load(); };
  const setConsentChoice = async (granted: boolean) => { const response = await fetch("/api/privacy/consent", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ granted }) }); if (response.ok) { setConsent(granted); setNotice(granted ? "Your acknowledgement has been recorded." : "Your acknowledgement has been withdrawn. Your account may need staff review before further processing."); } };
  return <div className="support-layout">
    <section className="paper-card emergency-notice"><span className="card-kicker">SAFETY FIRST</span><h2>This is not an emergency service.</h2><p>For chest pain, severe breathing trouble, loss of consciousness, suspected stroke, self-harm risk, or another immediate danger, call local emergency services or go to the nearest emergency department now. Do not wait for a reply here.</p></section>
    <section className="support-grid">
      <article className="paper-card support-form"><span className="card-kicker">CONTACT SUPPORT</span><h2>Get help from the team</h2><p>Account, data, billing, technical, or non-urgent safety.</p><form onSubmit={submit}><label>Topic<select name="category" defaultValue="general"><option value="general">General question</option><option value="technical">Technical problem</option><option value="data">My data or results</option><option value="billing">Billing or order</option><option value="account">Account access</option><option value="safety">Safety concern (not emergency)</option></select></label><label>Priority<select name="urgency" defaultValue="normal"><option value="normal">Normal</option><option value="priority">Priority</option></select></label><label>Subject<input name="subject" required minLength={3} maxLength={160} placeholder="What do you need help with?" /></label><label>Message<textarea name="message" required minLength={10} maxLength={4000} placeholder="Include enough detail for us to investigate. Do not share a password." /></label><button className="primary-button" disabled={saving} type="submit"><span>{saving ? "Sending…" : "Send to support"}</span><span>→</span></button></form>{notice ? <small className="support-notice" aria-live="polite">{notice}</small> : null}</article>
      <article className="paper-card privacy-card"><span className="card-kicker">PRIVACY & CONTROL</span><h2>Your health data stays yours.</h2><p>We use your profile, health inputs, uploaded files, check-ins, and chat history to provide your Twin, personalized program, safety review, and support. Access is limited to you and authorized Antiaging Labs staff operating the service.</p><ul><li>We retain active account records while your account is active.</li><li>Verified deletion requests are reviewed before processing; limited records may be retained where safety, payment, or law requires it.</li><li>We do not use your identifiable health information for research or marketing without a separate, revocable choice.</li></ul><label className="consent-toggle"><input checked={consent === true} onChange={(event) => void setConsentChoice(event.target.checked)} type="checkbox" /><span />I acknowledge this privacy notice and agree to processing needed to provide the service.</label><div className="rights-actions"><button className="secondary-button" onClick={() => void requestRight("export")} type="button">Request a copy of my data</button><button className="secondary-button" onClick={() => void requestRight("delete")} type="button">Request deletion</button></div><small>This is an operating notice for the founding beta and must receive local legal review before a broad public launch.</small></article>
    </section>
    <section className="support-history"><article className="paper-card"><span className="card-kicker">YOUR SUPPORT REQUESTS</span><h2>Support history</h2>{tickets.length ? tickets.map((ticket) => <div className="support-row" key={ticket.id}><span><strong>{ticket.subject}</strong><small>{ticket.category} · {new Date(ticket.created_at).toLocaleString()}</small></span><b>{ticket.status.replaceAll("_", " ")}</b></div>) : <p className="empty-copy">No support requests yet.</p>}</article><article className="paper-card"><span className="card-kicker">YOUR DATA REQUESTS</span><h2>Privacy requests</h2>{requests.length ? requests.map((request) => <div className="support-row" key={request.id}><span><strong>{request.request_type === "export" ? "Data copy" : "Deletion"}</strong><small>{new Date(request.created_at).toLocaleString()}</small></span><b>{request.status.replaceAll("_", " ")}</b></div>) : <p className="empty-copy">No privacy requests yet.</p>}</article></section>
  </div>;
}
