import { hashPassword, validPassword } from "@/lib/app-auth";
import { getDatabase, nowIso } from "@/lib/database";
import { runtimeConfig, timingSafeEqual } from "@/lib/integrations";
import { recomputeTwin } from "@/lib/twin-engine";

type Bundle = { email: string; fullName: string; primaryGoal: string; resetPassword?: string; intake: Array<{ questionCode: string; module: string; answer: unknown }>; observations: Array<{ conceptCode: string; domain: string; valueNumber?: number | null; valueText?: string | null; unit?: string | null; effectiveAt: string; source: string; quality?: string; provenance?: Record<string, unknown> }>; sources: Array<{ sourceCode: string; name: string; category: string; status: string; lastSyncAt?: string | null; coverage: number; metadata?: Record<string, unknown> }>; journey: Array<{ stepCode: string; title: string; detail: string; state: string; sortOrder: number }>; report: { title: string; sourceDate?: string | null; overview: string; deepDive: Record<string, unknown> }; protocol?: { title: string; strategy: string; startedAt: string; endsAt: string; actions: Array<{ domain: string; dayOfWeek?: number; scheduledTime?: string; title: string; detail: string; reason: string; target: string; sortOrder: number }> } };
const clean = (value: unknown, maximum = 1000) => typeof value === "string" ? value.trim().slice(0, maximum) : "";
const validEmail = (value: string) => value.length <= 254 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
async function stableId(prefix: string, value: string) { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); const hash = Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); return `${prefix}_${hash.slice(0, 28)}`; }
async function batches(database: D1Database, statements: D1PreparedStatement[]) { for (let index = 0; index < statements.length; index += 40) await database.batch(statements.slice(index, index + 40)); }

export async function POST(request: Request) {
  const key = runtimeConfig().MEMBER_IMPORT_KEY ?? "";
  if (!key || !timingSafeEqual(key, request.headers.get("x-member-import-key") ?? "")) return Response.json({ error: "Not authorized" }, { status: 401 });
  const body = await request.json().catch(() => ({})) as { members?: Bundle[] };
  if (!Array.isArray(body.members) || body.members.length !== 1) return Response.json({ error: "Provide exactly one member bundle" }, { status: 400 });
  const bundle = body.members[0]; const email = clean(bundle.email, 254).toLowerCase(); const fullName = clean(bundle.fullName, 120);
  if (!validEmail(email) || fullName.length < 2 || !validPassword(bundle.resetPassword)) return Response.json({ error: "A provisioned email, name, and 10+ character reset password are required" }, { status: 400 });
  const database = await getDatabase();
  const member = await database.prepare("SELECT id FROM members WHERE lower(email)=lower(?)").bind(email).first<{ id: string }>();
  if (!member) return Response.json({ error: "Create the account before importing" }, { status: 409 });
  const now = nowIso(); const password = await hashPassword(bundle.resetPassword); const statements: D1PreparedStatement[] = [
    database.prepare("UPDATE members SET full_name=?,primary_goal=?,updated_at=? WHERE id=?").bind(fullName, clean(bundle.primaryGoal), now, member.id),
    database.prepare("UPDATE auth_credentials SET password_hash=?,password_salt=?,updated_at=? WHERE member_id=?").bind(password.hash, password.salt, now, member.id),
    database.prepare("DELETE FROM auth_sessions WHERE member_id=?").bind(member.id),
    database.prepare("INSERT OR IGNORE INTO member_roles (member_id,role,created_at) VALUES (?,'member',?)").bind(member.id, now),
    database.prepare("INSERT INTO beta_access (member_id,status,requested_at,approved_at,note,updated_at) VALUES (?,'approved',?,?,?,?) ON CONFLICT(member_id) DO UPDATE SET status='approved',approved_at=excluded.approved_at,note=excluded.note,updated_at=excluded.updated_at").bind(member.id, now, now, "Founding cohort concierge onboarding", now),
  ];
  for (const item of bundle.journey) statements.push(database.prepare("INSERT INTO journey_steps (member_id,step_code,title,detail,state,sort_order,due_at,updated_at) VALUES (?,?,?,?,?,?,NULL,?) ON CONFLICT(member_id,step_code) DO UPDATE SET title=excluded.title,detail=excluded.detail,state=excluded.state,sort_order=excluded.sort_order,updated_at=excluded.updated_at").bind(member.id, clean(item.stepCode, 80), clean(item.title, 180), clean(item.detail, 500), clean(item.state, 20), item.sortOrder, now));
  for (const item of bundle.intake) statements.push(database.prepare("INSERT INTO intake_answers (member_id,question_code,module,answer_json,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(member_id,question_code) DO UPDATE SET module=excluded.module,answer_json=excluded.answer_json,updated_at=excluded.updated_at").bind(member.id, clean(item.questionCode, 120), clean(item.module, 80), JSON.stringify(item.answer), now));
  for (const item of bundle.sources) { const id = await stableId("source", `${member.id}:${item.sourceCode}`); statements.push(database.prepare("INSERT INTO data_sources (id,member_id,source_code,name,category,status,last_sync_at,coverage,metadata_json,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(member_id,source_code) DO UPDATE SET name=excluded.name,category=excluded.category,status=excluded.status,last_sync_at=excluded.last_sync_at,coverage=excluded.coverage,metadata_json=excluded.metadata_json,updated_at=excluded.updated_at").bind(id, member.id, clean(item.sourceCode, 120), clean(item.name, 180), clean(item.category, 80), clean(item.status, 80), item.lastSyncAt ?? null, Math.max(0, Math.min(100, Number(item.coverage) || 0)), JSON.stringify(item.metadata ?? {}), now)); }
  for (let index = 0; index < bundle.observations.length; index++) { const item = bundle.observations[index]; if (!item.conceptCode || !item.domain || (item.valueNumber === undefined && !item.valueText)) continue; const id = await stableId("obs", `${member.id}:${item.effectiveAt}:${item.source}:${item.conceptCode}:${index}`); statements.push(database.prepare("INSERT INTO observations (id,member_id,concept_code,domain,value_number,value_text,unit,effective_at,source,quality,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET concept_code=excluded.concept_code,domain=excluded.domain,value_number=excluded.value_number,value_text=excluded.value_text,unit=excluded.unit,effective_at=excluded.effective_at,source=excluded.source,quality=excluded.quality,metadata_json=excluded.metadata_json").bind(id, member.id, clean(item.conceptCode, 120), clean(item.domain, 80), typeof item.valueNumber === "number" && Number.isFinite(item.valueNumber) ? item.valueNumber : null, item.valueText ?? null, item.unit ?? null, item.effectiveAt, clean(item.source, 180), item.quality === "needs_review" ? "needs_review" : "accepted", JSON.stringify({ ...(item.provenance ?? {}), importedBy: "concierge", importedAt: now }), now)); }
  const reportId = await stableId("report", `${member.id}:tessera-biomarkers:${bundle.report.sourceDate ?? "unknown"}`);
  statements.push(database.prepare("INSERT INTO reports (id,member_id,type,title,status,source_date,overview,deep_dive_json,created_at,updated_at) VALUES (?,?,'biomarkers',?,'ready',?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,status='ready',source_date=excluded.source_date,overview=excluded.overview,deep_dive_json=excluded.deep_dive_json,updated_at=excluded.updated_at").bind(reportId, member.id, clean(bundle.report.title, 240), bundle.report.sourceDate ?? null, clean(bundle.report.overview, 4000), JSON.stringify(bundle.report.deepDive), now, now));
  if (bundle.protocol) { const protocolId = await stableId("protocol", `${member.id}:tessera-final-protocol`); statements.push(database.prepare("UPDATE protocol_versions SET status='superseded',updated_at=? WHERE member_id=? AND status='current' AND id<>?").bind(now, member.id, protocolId)); statements.push(database.prepare("INSERT INTO protocol_versions (id,member_id,version,status,title,strategy,started_at,ends_at,created_at,updated_at) VALUES (?,?,1,'current',?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status='current',title=excluded.title,strategy=excluded.strategy,started_at=excluded.started_at,ends_at=excluded.ends_at,updated_at=excluded.updated_at").bind(protocolId, member.id, clean(bundle.protocol.title, 240), clean(bundle.protocol.strategy, 4000), bundle.protocol.startedAt, bundle.protocol.endsAt, now, now)); statements.push(database.prepare("DELETE FROM protocol_actions WHERE protocol_id=? AND member_id=?").bind(protocolId, member.id)); for (const action of bundle.protocol.actions) statements.push(database.prepare("INSERT INTO protocol_actions (protocol_id,member_id,domain,day_of_week,scheduled_time,title,detail,reason,target,done,done_at,sort_order) VALUES (?,?,?,?,?,?,?,?,?,0,NULL,?)").bind(protocolId, member.id, clean(action.domain, 80), action.dayOfWeek ?? 0, clean(action.scheduledTime ?? "08:00", 20), clean(action.title, 240), clean(action.detail, 3000), clean(action.reason, 2000), clean(action.target, 1000), action.sortOrder)); }
  statements.push(database.prepare("INSERT INTO admin_events (member_id,actor_id,action,entity_type,entity_id,detail_json,created_at) VALUES (?,'system:concierge-import','member_bundle_imported','member',?,?,?)").bind(member.id, member.id, JSON.stringify({ reportId, observationCount: bundle.observations.length, intakeCount: bundle.intake.length, protocolImported: Boolean(bundle.protocol), passwordReset: true }), now));
  await batches(database, statements); await recomputeTwin(member.id);
  return Response.json({ imported: { email, memberId: member.id, observations: bundle.observations.length, intake: bundle.intake.length, reportId, protocol: Boolean(bundle.protocol) } });
}
