import { env } from "cloudflare:workers";

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS members (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, full_name TEXT NOT NULL, primary_goal TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS auth_credentials (member_id TEXT PRIMARY KEY, password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS auth_sessions (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, last_seen_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_auth_sessions_member ON auth_sessions(member_id)`,
  `CREATE INDEX IF NOT EXISTS idx_auth_sessions_expiry ON auth_sessions(expires_at)`,
  `CREATE TABLE IF NOT EXISTS beta_access (member_id TEXT PRIMARY KEY, status TEXT NOT NULL, requested_at TEXT, approved_at TEXT, note TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_beta_access_status ON beta_access(status)`,
  `CREATE TABLE IF NOT EXISTS journey_steps (id INTEGER PRIMARY KEY AUTOINCREMENT, member_id TEXT NOT NULL, step_code TEXT NOT NULL, title TEXT NOT NULL, detail TEXT NOT NULL, state TEXT NOT NULL, sort_order INTEGER NOT NULL, due_at TEXT, updated_at TEXT NOT NULL, UNIQUE(member_id, step_code))`,
  `CREATE INDEX IF NOT EXISTS idx_journey_member_order ON journey_steps(member_id, sort_order)`,
  `CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, type TEXT NOT NULL, product_name TEXT NOT NULL, status TEXT NOT NULL, reference TEXT NOT NULL, vendor TEXT, amount_paise INTEGER NOT NULL, payment_status TEXT NOT NULL, tracking_url TEXT, appointment_at TEXT, metadata_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_orders_member_updated ON orders(member_id, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)`,
  `CREATE TABLE IF NOT EXISTS intake_answers (id INTEGER PRIMARY KEY AUTOINCREMENT, member_id TEXT NOT NULL, question_code TEXT NOT NULL, module TEXT NOT NULL, answer_json TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(member_id, question_code))`,
  `CREATE INDEX IF NOT EXISTS idx_intake_member_module ON intake_answers(member_id, module)`,
  `CREATE TABLE IF NOT EXISTS data_sources (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, source_code TEXT NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL, status TEXT NOT NULL, last_sync_at TEXT, coverage REAL NOT NULL, metadata_json TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(member_id, source_code))`,
  `CREATE INDEX IF NOT EXISTS idx_sources_member_status ON data_sources(member_id, status)`,
  `CREATE TABLE IF NOT EXISTS observations (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, concept_code TEXT NOT NULL, domain TEXT NOT NULL, value_number REAL, value_text TEXT, unit TEXT, effective_at TEXT NOT NULL, source TEXT NOT NULL, quality TEXT NOT NULL, metadata_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_observations_member_domain_time ON observations(member_id, domain, effective_at)`,
  `CREATE INDEX IF NOT EXISTS idx_observations_member_concept_time ON observations(member_id, concept_code, effective_at)`,
  `CREATE TABLE IF NOT EXISTS twin_snapshots (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, version INTEGER NOT NULL, as_of TEXT NOT NULL, coverage REAL NOT NULL, summary TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(member_id, version))`,
  `CREATE INDEX IF NOT EXISTS idx_twin_member_asof ON twin_snapshots(member_id, as_of)`,
  `CREATE TABLE IF NOT EXISTS twin_domains (id INTEGER PRIMARY KEY AUTOINCREMENT, snapshot_id TEXT NOT NULL, member_id TEXT NOT NULL, domain_code TEXT NOT NULL, label TEXT NOT NULL, status TEXT NOT NULL, state_label TEXT NOT NULL, trend TEXT NOT NULL, confidence REAL NOT NULL, freshness TEXT NOT NULL, key_metric TEXT NOT NULL, key_value TEXT NOT NULL, key_unit TEXT, target TEXT, evidence_json TEXT NOT NULL, UNIQUE(snapshot_id, domain_code))`,
  `CREATE INDEX IF NOT EXISTS idx_twin_domains_member ON twin_domains(member_id)`,
  `CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, source_date TEXT, overview TEXT NOT NULL, deep_dive_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_reports_member_updated ON reports(member_id, updated_at)`,
  `CREATE TABLE IF NOT EXISTS protocol_versions (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, version INTEGER NOT NULL, status TEXT NOT NULL, title TEXT NOT NULL, strategy TEXT NOT NULL, started_at TEXT NOT NULL, ends_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(member_id, version))`,
  `CREATE INDEX IF NOT EXISTS idx_protocol_member_status ON protocol_versions(member_id, status)`,
  `CREATE TABLE IF NOT EXISTS protocol_actions (id INTEGER PRIMARY KEY AUTOINCREMENT, protocol_id TEXT NOT NULL, member_id TEXT NOT NULL, domain TEXT NOT NULL, day_of_week INTEGER NOT NULL, scheduled_time TEXT NOT NULL, title TEXT NOT NULL, detail TEXT NOT NULL, reason TEXT NOT NULL, target TEXT NOT NULL, done INTEGER NOT NULL DEFAULT 0, done_at TEXT, sort_order INTEGER NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_actions_member_protocol_order ON protocol_actions(member_id, protocol_id, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_actions_member_done ON protocol_actions(member_id, done)`,
  `CREATE TABLE IF NOT EXISTS chat_messages (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, conversation_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, sources_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_chat_member_conversation_time ON chat_messages(member_id, conversation_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS uploads (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, type TEXT NOT NULL, object_key TEXT NOT NULL, file_name TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_uploads_member_created ON uploads(member_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS webhook_events (id TEXT PRIMARY KEY, provider TEXT NOT NULL, event_type TEXT NOT NULL, payload_json TEXT NOT NULL, status TEXT NOT NULL, received_at TEXT NOT NULL, processed_at TEXT)`,
  `CREATE INDEX IF NOT EXISTS idx_webhooks_provider_status ON webhook_events(provider, status)`,
  `CREATE TABLE IF NOT EXISTS admin_events (id INTEGER PRIMARY KEY AUTOINCREMENT, member_id TEXT, actor_id TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, detail_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_admin_events_created ON admin_events(created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_admin_events_member ON admin_events(member_id)`,
  `CREATE TABLE IF NOT EXISTS member_roles (id INTEGER PRIMARY KEY AUTOINCREMENT, member_id TEXT NOT NULL, role TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(member_id, role))`,
  `CREATE TABLE IF NOT EXISTS catalog_versions (id TEXT PRIMARY KEY, code TEXT NOT NULL, version INTEGER NOT NULL, type TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, amount_paise INTEGER NOT NULL, tax_paise INTEGER NOT NULL, city TEXT NOT NULL, turnaround_days INTEGER NOT NULL, preparation_json TEXT NOT NULL, cancellation_policy TEXT NOT NULL, active INTEGER NOT NULL, created_at TEXT NOT NULL, UNIQUE(code, version))`,
  `CREATE INDEX IF NOT EXISTS idx_catalog_active_type ON catalog_versions(active, type)`,
  `CREATE TABLE IF NOT EXISTS order_events (id TEXT PRIMARY KEY, order_id TEXT NOT NULL, member_id TEXT NOT NULL, status TEXT NOT NULL, actor_id TEXT NOT NULL, source TEXT NOT NULL, public_message TEXT NOT NULL, internal_note TEXT NOT NULL, occurred_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_order_events_order_time ON order_events(order_id, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS idx_order_events_member_time ON order_events(member_id, occurred_at)`,
  `CREATE TABLE IF NOT EXISTS payment_attempts (id TEXT PRIMARY KEY, order_id TEXT NOT NULL, member_id TEXT NOT NULL, provider TEXT NOT NULL, provider_order_id TEXT, provider_payment_id TEXT, amount_paise INTEGER NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, idempotency_key TEXT NOT NULL, detail_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(member_id, idempotency_key))`,
  `CREATE INDEX IF NOT EXISTS idx_payments_provider_order ON payment_attempts(provider_order_id)`,
  `CREATE TABLE IF NOT EXISTS consent_records (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, purpose TEXT NOT NULL, notice_version TEXT NOT NULL, granted INTEGER NOT NULL, evidence_json TEXT NOT NULL, granted_at TEXT, revoked_at TEXT, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_consents_member_purpose ON consent_records(member_id, purpose)`,
  `CREATE TABLE IF NOT EXISTS wearable_connections (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, provider TEXT NOT NULL, status TEXT NOT NULL, external_user_id TEXT, encrypted_token_json TEXT, scopes_json TEXT NOT NULL, cursor TEXT, last_sync_at TEXT, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(member_id, provider))`,
  `CREATE INDEX IF NOT EXISTS idx_connections_status_sync ON wearable_connections(status, last_sync_at)`,
  `CREATE TABLE IF NOT EXISTS oauth_states (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, provider TEXT NOT NULL, verifier TEXT NOT NULL, redirect_uri TEXT NOT NULL, expires_at TEXT NOT NULL, consumed_at TEXT, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_oauth_states_member_provider ON oauth_states(member_id, provider)`,
  `CREATE TABLE IF NOT EXISTS wearable_daily (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, provider TEXT NOT NULL, day TEXT NOT NULL, timezone TEXT NOT NULL, sleep_minutes REAL, sleep_score REAL, hrv_rmssd REAL, resting_hr REAL, steps REAL, active_calories REAL, workout_minutes REAL, quality REAL NOT NULL, raw_hash TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(member_id, provider, day))`,
  `CREATE INDEX IF NOT EXISTS idx_wearable_daily_member_day ON wearable_daily(member_id, day)`,
  `CREATE TABLE IF NOT EXISTS observation_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, observation_id TEXT NOT NULL, member_id TEXT NOT NULL, status TEXT NOT NULL, reviewer_id TEXT NOT NULL, previous_json TEXT NOT NULL, note TEXT NOT NULL, reviewed_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_observation_reviews_observation ON observation_reviews(observation_id)`,
  `CREATE TABLE IF NOT EXISTS processing_jobs (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, upload_id TEXT NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, progress INTEGER NOT NULL, result_json TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_jobs_member_status ON processing_jobs(member_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_jobs_upload ON processing_jobs(upload_id)`,
  `CREATE TABLE IF NOT EXISTS approvals (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, role TEXT NOT NULL, status TEXT NOT NULL, reviewer_id TEXT, note TEXT NOT NULL, created_at TEXT NOT NULL, decided_at TEXT)`,
  `CREATE INDEX IF NOT EXISTS idx_approvals_entity ON approvals(entity_type, entity_id)`,
  `CREATE INDEX IF NOT EXISTS idx_approvals_status_role ON approvals(status, role)`,
  `CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, channel TEXT NOT NULL, template TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL, sent_at TEXT)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_member_created ON notifications(member_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications(status)`,
  `CREATE TABLE IF NOT EXISTS daily_adjustments (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, protocol_id TEXT NOT NULL, day TEXT NOT NULL, knob TEXT NOT NULL, previous_value TEXT NOT NULL, adjusted_value TEXT NOT NULL, rationale TEXT NOT NULL, twin_snapshot_id TEXT NOT NULL, accepted INTEGER NOT NULL, created_at TEXT NOT NULL, UNIQUE(member_id, day))`,
  `CREATE TABLE IF NOT EXISTS chat_audits (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, message_id TEXT NOT NULL, snapshot_hash TEXT NOT NULL, fields_json TEXT NOT NULL, grounding_json TEXT NOT NULL, model TEXT NOT NULL, policy_version TEXT NOT NULL, safety_class TEXT NOT NULL, outcome TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(message_id))`,
  `CREATE INDEX IF NOT EXISTS idx_chat_audits_member_time ON chat_audits(member_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS genomic_artifacts (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, upload_id TEXT, kind TEXT NOT NULL, format TEXT NOT NULL, genome_build TEXT, sample_id TEXT, object_key TEXT NOT NULL, checksum_sha256 TEXT NOT NULL, size INTEGER NOT NULL, status TEXT NOT NULL, qc_json TEXT NOT NULL, pipeline_version TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_genomic_artifacts_member_created ON genomic_artifacts(member_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_genomic_artifacts_status ON genomic_artifacts(status)`,
  `CREATE TABLE IF NOT EXISTS genomic_variant_calls (id TEXT PRIMARY KEY, artifact_id TEXT NOT NULL, member_id TEXT NOT NULL, rsid TEXT, chromosome TEXT NOT NULL, position INTEGER NOT NULL, reference_allele TEXT, alternate_allele TEXT, genotype TEXT, phased INTEGER NOT NULL, call_state TEXT NOT NULL, filter TEXT, quality REAL, metadata_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_variant_calls_artifact ON genomic_variant_calls(artifact_id)`,
  `CREATE INDEX IF NOT EXISTS idx_variant_calls_member_rsid ON genomic_variant_calls(member_id, rsid)`,
  `CREATE INDEX IF NOT EXISTS idx_variant_calls_member_position ON genomic_variant_calls(member_id, chromosome, position)`,
  `CREATE TABLE IF NOT EXISTS evidence_releases (id TEXT PRIMARY KEY, source TEXT NOT NULL, version TEXT NOT NULL, released_at TEXT NOT NULL, checksum TEXT NOT NULL, status TEXT NOT NULL, metadata_json TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(source, version))`,
  `CREATE TABLE IF NOT EXISTS genomic_interpretations (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, artifact_id TEXT NOT NULL, variant_call_id TEXT, gene TEXT NOT NULL, rsid TEXT NOT NULL, category TEXT NOT NULL, title TEXT NOT NULL, summary TEXT NOT NULL, evidence_level TEXT NOT NULL, evidence_release_ids_json TEXT NOT NULL, limitations_json TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_interpretations_member_status ON genomic_interpretations(member_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_interpretations_artifact ON genomic_interpretations(artifact_id)`,
  `CREATE TABLE IF NOT EXISTS genomic_reanalysis_runs (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, artifact_id TEXT NOT NULL, previous_run_id TEXT, trigger TEXT NOT NULL, evidence_set_json TEXT NOT NULL, pipeline_version TEXT NOT NULL, status TEXT NOT NULL, summary_json TEXT NOT NULL, created_at TEXT NOT NULL, completed_at TEXT)`,
  `CREATE INDEX IF NOT EXISTS idx_reanalysis_member_created ON genomic_reanalysis_runs(member_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_reanalysis_artifact ON genomic_reanalysis_runs(artifact_id)`,
  `CREATE TABLE IF NOT EXISTS cross_modal_findings (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, snapshot_id TEXT NOT NULL, domain_code TEXT NOT NULL, title TEXT NOT NULL, statement TEXT NOT NULL, direction TEXT NOT NULL, confidence REAL NOT NULL, layers_json TEXT NOT NULL, evidence_refs_json TEXT NOT NULL, missing_json TEXT NOT NULL, method_version TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(snapshot_id, domain_code, title))`,
  `CREATE INDEX IF NOT EXISTS idx_cross_modal_member_snapshot ON cross_modal_findings(member_id, snapshot_id)`,
  `CREATE TABLE IF NOT EXISTS ai_draft_runs (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, task TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, input_hash TEXT NOT NULL, input_refs_json TEXT NOT NULL, model TEXT NOT NULL, prompt_version TEXT NOT NULL, policy_version TEXT NOT NULL, output_json TEXT NOT NULL, status TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_ai_drafts_member_created ON ai_draft_runs(member_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_ai_drafts_entity ON ai_draft_runs(entity_type, entity_id)`,
  `CREATE TABLE IF NOT EXISTS chat_reviews (id TEXT PRIMARY KEY, audit_id TEXT NOT NULL UNIQUE, member_id TEXT NOT NULL, reviewer_id TEXT NOT NULL, verdict TEXT NOT NULL, correction TEXT NOT NULL, note TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_chat_reviews_member_created ON chat_reviews(member_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS lab_integration_events (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, order_id TEXT, provider TEXT NOT NULL, external_reference TEXT, event_type TEXT NOT NULL, idempotency_key TEXT NOT NULL, status TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, processed_at TEXT, UNIQUE(provider, idempotency_key))`,
  `CREATE INDEX IF NOT EXISTS idx_lab_events_member_created ON lab_integration_events(member_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS companion_pairing_codes (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, code_hash TEXT NOT NULL UNIQUE, platform TEXT NOT NULL, expires_at TEXT NOT NULL, consumed_at TEXT, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_pairing_member_expiry ON companion_pairing_codes(member_id, expires_at)`,
  `CREATE TABLE IF NOT EXISTS device_installations (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, platform TEXT NOT NULL, device_name TEXT NOT NULL, app_version TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, status TEXT NOT NULL, last_sync_at TEXT, last_cursor TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_installations_member_status ON device_installations(member_id, status)`,
  `CREATE TABLE IF NOT EXISTS native_sync_batches (id TEXT PRIMARY KEY, installation_id TEXT NOT NULL, member_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, platform_cursor TEXT, sample_count INTEGER NOT NULL, inserted_count INTEGER NOT NULL, deleted_count INTEGER NOT NULL, status TEXT NOT NULL, error TEXT, received_at TEXT NOT NULL, completed_at TEXT, UNIQUE(installation_id, idempotency_key))`,
  `CREATE INDEX IF NOT EXISTS idx_native_batch_member_time ON native_sync_batches(member_id, received_at)`,
  `CREATE TABLE IF NOT EXISTS native_health_samples (id TEXT PRIMARY KEY, installation_id TEXT NOT NULL, member_id TEXT NOT NULL, platform TEXT NOT NULL, external_id TEXT NOT NULL, type_code TEXT NOT NULL, value_number REAL, unit TEXT, start_at TEXT NOT NULL, end_at TEXT NOT NULL, timezone TEXT NOT NULL, source_name TEXT NOT NULL, source_bundle TEXT NOT NULL, device_json TEXT NOT NULL, metadata_json TEXT NOT NULL, deleted_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(installation_id, external_id))`,
  `CREATE INDEX IF NOT EXISTS idx_native_samples_member_type_time ON native_health_samples(member_id, type_code, start_at)`,
  `CREATE TABLE IF NOT EXISTS connector_sync_runs (id TEXT PRIMARY KEY, member_id TEXT, provider TEXT NOT NULL, trigger TEXT NOT NULL, status TEXT NOT NULL, cursor_before TEXT, cursor_after TEXT, records_read INTEGER NOT NULL, records_written INTEGER NOT NULL, latency_ms INTEGER NOT NULL, error_code TEXT, started_at TEXT NOT NULL, completed_at TEXT)`,
  `CREATE INDEX IF NOT EXISTS idx_connector_runs_provider_time ON connector_sync_runs(provider, started_at)`,
  `CREATE INDEX IF NOT EXISTS idx_connector_runs_member_time ON connector_sync_runs(member_id, started_at)`,
  `CREATE TABLE IF NOT EXISTS research_consents (id TEXT PRIMARY KEY, member_id TEXT NOT NULL UNIQUE, notice_version TEXT NOT NULL, granted INTEGER NOT NULL, scopes_json TEXT NOT NULL, granted_at TEXT, revoked_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS outcome_measurements (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, target_code TEXT NOT NULL, window_code TEXT NOT NULL, baseline_value REAL NOT NULL, current_value REAL NOT NULL, absolute_change REAL NOT NULL, percent_change REAL, unit TEXT NOT NULL, baseline_at TEXT NOT NULL, current_at TEXT NOT NULL, adherence REAL, quality REAL NOT NULL, source_refs_json TEXT NOT NULL, computed_at TEXT NOT NULL, UNIQUE(member_id, target_code, window_code))`,
  `CREATE INDEX IF NOT EXISTS idx_outcome_target_time ON outcome_measurements(target_code, computed_at)`,
  `CREATE TABLE IF NOT EXISTS response_model_versions (id TEXT PRIMARY KEY, target_code TEXT NOT NULL, version INTEGER NOT NULL, status TEXT NOT NULL, feature_codes_json TEXT NOT NULL, coefficients_json TEXT NOT NULL, training_window_json TEXT NOT NULL, metrics_json TEXT NOT NULL, calibration_json TEXT NOT NULL, subgroup_json TEXT NOT NULL, abstention_json TEXT NOT NULL, data_snapshot_hash TEXT NOT NULL, created_at TEXT NOT NULL, published_at TEXT, UNIQUE(target_code, version))`,
  `CREATE INDEX IF NOT EXISTS idx_response_model_target_status ON response_model_versions(target_code, status)`,
  `CREATE TABLE IF NOT EXISTS response_predictions (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, model_version_id TEXT NOT NULL, target_code TEXT NOT NULL, estimate REAL, lower_bound REAL, upper_bound REAL, confidence REAL NOT NULL, status TEXT NOT NULL, abstention_reason TEXT, feature_snapshot_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_predictions_member_target_time ON response_predictions(member_id, target_code, created_at)`,
  `CREATE TABLE IF NOT EXISTS response_model_evaluations (id TEXT PRIMARY KEY, model_version_id TEXT NOT NULL, study_id TEXT NOT NULL, dataset_hash TEXT NOT NULL, cohort_n INTEGER NOT NULL, metrics_json TEXT NOT NULL, calibration_json TEXT NOT NULL, subgroup_json TEXT NOT NULL, status TEXT NOT NULL, evaluator_id TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(model_version_id, study_id))`,
  `CREATE INDEX IF NOT EXISTS idx_model_evaluation_status ON response_model_evaluations(status, created_at)`,
  `CREATE TABLE IF NOT EXISTS experiments (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, template_code TEXT NOT NULL, title TEXT NOT NULL, hypothesis TEXT NOT NULL, primary_outcome TEXT NOT NULL, unit TEXT NOT NULL, status TEXT NOT NULL, design TEXT NOT NULL, start_at TEXT NOT NULL, end_at TEXT NOT NULL, protocol_snapshot_id TEXT, result_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_experiments_member_status ON experiments(member_id, status)`,
  `CREATE TABLE IF NOT EXISTS experiment_periods (id TEXT PRIMARY KEY, experiment_id TEXT NOT NULL, member_id TEXT NOT NULL, day TEXT NOT NULL, arm TEXT NOT NULL, instruction TEXT NOT NULL, completed INTEGER NOT NULL, adherence REAL, outcome_value REAL, context_json TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(experiment_id, day))`,
  `CREATE INDEX IF NOT EXISTS idx_experiment_period_member_day ON experiment_periods(member_id, day)`,
  `CREATE TABLE IF NOT EXISTS member_jurisdictions (member_id TEXT PRIMARY KEY, country_code TEXT NOT NULL, region_code TEXT NOT NULL, policy_version TEXT NOT NULL, features_json TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS fhir_exports (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, standard TEXT NOT NULL, profile_version TEXT NOT NULL, purpose TEXT NOT NULL, bundle_hash TEXT NOT NULL, object_key TEXT, status TEXT NOT NULL, destination TEXT, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_fhir_exports_member_time ON fhir_exports(member_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS backup_runs (id TEXT PRIMARY KEY, object_key TEXT NOT NULL, status TEXT NOT NULL, table_count INTEGER NOT NULL, row_count INTEGER NOT NULL, bytes INTEGER NOT NULL, checksum_sha256 TEXT NOT NULL, triggered_by TEXT NOT NULL, created_at TEXT NOT NULL, verified_at TEXT, error TEXT)`,
  `CREATE INDEX IF NOT EXISTS idx_backup_runs_status_created ON backup_runs(status, created_at)`,
  `CREATE TABLE IF NOT EXISTS member_goals (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, statement TEXT NOT NULL, desired_outcome TEXT NOT NULL, importance INTEGER NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_member_goals_member_status ON member_goals(member_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_member_goals_member_updated ON member_goals(member_id, updated_at)`,
  `CREATE TABLE IF NOT EXISTS safety_decisions (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, status TEXT NOT NULL, reason_codes_json TEXT NOT NULL, evidence_refs_json TEXT NOT NULL, policy_version TEXT NOT NULL, decided_by TEXT NOT NULL, decided_at TEXT NOT NULL, expires_at TEXT, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_safety_member_status ON safety_decisions(member_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_safety_entity_time ON safety_decisions(entity_type, entity_id, decided_at)`,
  `CREATE TABLE IF NOT EXISTS priority_assessments (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, goal_id TEXT, twin_snapshot_id TEXT, safety_decision_id TEXT, recommended_candidate_id TEXT, status TEXT NOT NULL, engine_version TEXT NOT NULL, evidence_version TEXT NOT NULL, input_snapshot_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_priority_assessments_member_time ON priority_assessments(member_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_priority_assessments_status ON priority_assessments(status, created_at)`,
  `CREATE TABLE IF NOT EXISTS priority_candidates (id TEXT PRIMARY KEY, assessment_id TEXT NOT NULL, member_id TEXT NOT NULL, candidate_code TEXT NOT NULL, domain_code TEXT NOT NULL, title TEXT NOT NULL, user_importance REAL NOT NULL, actionability REAL NOT NULL, measurement_readiness REAL NOT NULL, evidence_confidence REAL NOT NULL, time_to_signal REAL NOT NULL, burden REAL NOT NULL, risk_penalty REAL NOT NULL, genetics_modifier REAL NOT NULL, final_score REAL NOT NULL, rank INTEGER NOT NULL, rationale_json TEXT NOT NULL, evidence_refs_json TEXT NOT NULL, missing_json TEXT NOT NULL, experiment_templates_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_priority_candidate_assessment_code ON priority_candidates(assessment_id, candidate_code)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_priority_candidate_assessment_rank ON priority_candidates(assessment_id, rank)`,
  `CREATE INDEX IF NOT EXISTS idx_priority_candidates_member_score ON priority_candidates(member_id, final_score)`,
  `CREATE TABLE IF NOT EXISTS intervention_episodes (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, goal_id TEXT, priority_candidate_id TEXT, safety_decision_id TEXT NOT NULL, source_experiment_id TEXT, source_protocol_action_id INTEGER, title TEXT NOT NULL, category TEXT NOT NULL, hypothesis TEXT NOT NULL, exact_instruction TEXT NOT NULL, dose_or_duration TEXT, frequency TEXT NOT NULL, primary_outcome_code TEXT NOT NULL, outcome_direction TEXT NOT NULL, outcome_unit TEXT NOT NULL, target_min REAL, target_max REAL, minimum_baseline_days INTEGER NOT NULL, minimum_comparison_days INTEGER NOT NULL, start_at TEXT, end_at TEXT, review_at TEXT NOT NULL, evidence_version TEXT NOT NULL, status TEXT NOT NULL, decision TEXT, decision_reason TEXT, decided_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_interventions_member_status_review ON intervention_episodes(member_id, status, review_at)`,
  `CREATE INDEX IF NOT EXISTS idx_interventions_candidate ON intervention_episodes(priority_candidate_id)`,
  `CREATE INDEX IF NOT EXISTS idx_interventions_outcome ON intervention_episodes(primary_outcome_code, status)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_interventions_one_active_member ON intervention_episodes(member_id) WHERE status = 'active'`,
  `CREATE TABLE IF NOT EXISTS intervention_exposures (id TEXT PRIMARY KEY, intervention_episode_id TEXT NOT NULL, member_id TEXT NOT NULL, scheduled_at TEXT NOT NULL, occurred_at TEXT, planned_value TEXT, actual_value TEXT, adherence REAL NOT NULL, completed INTEGER NOT NULL, subjective_response REAL, adverse_effect INTEGER NOT NULL, note TEXT NOT NULL, source TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_exposure_episode_schedule ON intervention_exposures(intervention_episode_id, scheduled_at)`,
  `CREATE INDEX IF NOT EXISTS idx_exposures_member_time ON intervention_exposures(member_id, scheduled_at)`,
  `CREATE INDEX IF NOT EXISTS idx_exposures_episode_completed ON intervention_exposures(intervention_episode_id, completed)`,
  `CREATE TABLE IF NOT EXISTS context_events (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, intervention_episode_id TEXT, occurred_at TEXT NOT NULL, type TEXT NOT NULL, severity INTEGER NOT NULL, detail_json TEXT NOT NULL, source TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_context_member_time ON context_events(member_id, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS idx_context_episode_time ON context_events(intervention_episode_id, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS idx_context_type_time ON context_events(type, occurred_at)`,
  `CREATE TABLE IF NOT EXISTS response_assessments (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, intervention_episode_id TEXT NOT NULL, version INTEGER NOT NULL, status TEXT NOT NULL, primary_outcome_code TEXT NOT NULL, outcome_direction TEXT NOT NULL, unit TEXT NOT NULL, baseline_start TEXT NOT NULL, baseline_end TEXT NOT NULL, comparison_start TEXT NOT NULL, comparison_end TEXT NOT NULL, baseline_value REAL, comparison_value REAL, absolute_change REAL, percent_change REAL, effect_estimate REAL, lower_bound REAL, upper_bound REAL, data_quality REAL NOT NULL, adherence REAL NOT NULL, baseline_usable_days INTEGER NOT NULL, comparison_usable_days INTEGER NOT NULL, confounders_json TEXT NOT NULL, attribution_grade TEXT NOT NULL, conclusion TEXT NOT NULL, recommended_decision TEXT NOT NULL, insufficiency_reasons_json TEXT NOT NULL, source_refs_json TEXT NOT NULL, analysis_version TEXT NOT NULL, computed_at TEXT NOT NULL, reviewed_at TEXT)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_response_assessment_episode_version ON response_assessments(intervention_episode_id, version)`,
  `CREATE INDEX IF NOT EXISTS idx_response_assessments_member_time ON response_assessments(member_id, computed_at)`,
  `CREATE INDEX IF NOT EXISTS idx_response_assessments_status_time ON response_assessments(status, computed_at)`,
  `CREATE INDEX IF NOT EXISTS idx_response_assessments_outcome_time ON response_assessments(primary_outcome_code, computed_at)`,
  `CREATE TABLE IF NOT EXISTS genetic_hypothesis_links (id TEXT PRIMARY KEY, member_id TEXT NOT NULL, intervention_episode_id TEXT NOT NULL, genomic_interpretation_id TEXT NOT NULL, influence TEXT NOT NULL, predicted_relationship TEXT NOT NULL, observed_status TEXT NOT NULL, evidence_version TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_genetic_link_intervention_interpretation ON genetic_hypothesis_links(intervention_episode_id, genomic_interpretation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_genetic_links_member_status ON genetic_hypothesis_links(member_id, observed_status)`,
  `CREATE INDEX IF NOT EXISTS idx_genetic_links_interpretation ON genetic_hypothesis_links(genomic_interpretation_id)`,
  `CREATE TABLE IF NOT EXISTS product_events (id TEXT PRIMARY KEY, member_id TEXT, event_name TEXT NOT NULL, journey_state TEXT, source TEXT NOT NULL, cohort_code TEXT, session_id TEXT, schema_version TEXT NOT NULL, occurred_at TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_product_events_name_time ON product_events(event_name, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS idx_product_events_member_time ON product_events(member_id, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS idx_product_events_cohort_name ON product_events(cohort_code, event_name)`,
];

let initialized = false;

export async function getDatabase(): Promise<D1Database> {
  const database = env.DB;
  if (!database) throw new Error("Database binding DB is unavailable");
  if (!initialized) {
    await database.batch(schemaStatements.map((statement) => database.prepare(statement)));
    await database.prepare("PRAGMA optimize").run();
    initialized = true;
  }
  return database;
}

export function nowIso(): string {
  return new Date().toISOString();
}

export function id(prefix: string): string {
  return `${prefix}_${crypto.randomUUID().replaceAll("-", "")}`;
}

export function parseJson<T>(value: unknown, fallback: T): T {
  if (typeof value !== "string") return fallback;
  try { return JSON.parse(value) as T; } catch { return fallback; }
}
