export type IntakeQuestion={code:string;module:string;label:string;type:"text"|"number"|"textarea";why:string;sensitive?:boolean;required?:boolean;showIf?:{code:string;includes:string[]}};
export const intakeQuestions:IntakeQuestion[]=[
{code:"primary_goal",module:"goals",label:"What is your main health goal right now?",type:"textarea",why:"Anchors protocol priorities.",required:true},
{code:"desired_outcomes",module:"goals",label:"What would meaningful progress look like in 12 weeks?",type:"textarea",why:"Turns broad goals into measurable outcomes."},
{code:"birth_sex",module:"identity",label:"Sex recorded at birth",type:"text",why:"Used where reference ranges or physiology differ.",sensitive:true,required:true},
{code:"reproductive_context",module:"identity",label:"Relevant menstrual, menopause, pregnancy, breastfeeding, or hormone context",type:"textarea",why:"Adds important physiological context.",sensitive:true},
{code:"height",module:"body",label:"Height (cm)",type:"number",why:"Used for body-composition and derived calculations.",required:true},
{code:"weight",module:"body",label:"Weight (kg)",type:"number",why:"Supports body-composition and training targets.",required:true},
{code:"waist",module:"body",label:"Waist circumference (cm)",type:"number",why:"A useful longitudinal cardiometabolic measure."},
{code:"blood_pressure",module:"body",label:"Recent blood pressure and measurement context",type:"text",why:"Adds cardiovascular context."},
{code:"diagnoses",module:"medical",label:"Current diagnoses or ongoing medical conditions",type:"textarea",why:"Shapes interpretation and recommendation constraints.",sensitive:true},
{code:"surgeries",module:"medical",label:"Past surgeries or major procedures",type:"textarea",why:"Adds relevant history.",sensitive:true},
{code:"hospitalizations",module:"medical",label:"Recent hospitalizations or emergency visits",type:"textarea",why:"Identifies recent health changes.",sensitive:true},
{code:"medications",module:"medical",label:"Current medications, doses, and timing",type:"textarea",why:"Allows interaction and schedule checks.",sensitive:true,required:true},
{code:"supplements",module:"medical",label:"Current supplements, doses, and timing",type:"textarea",why:"Keeps the protocol measurable and avoids duplication.",sensitive:true},
{code:"allergies",module:"medical",label:"Allergies or past adverse reactions",type:"textarea",why:"Prevents incompatible suggestions.",sensitive:true,required:true},
{code:"acute_symptoms",module:"safety",label:"Any new, severe, or worsening symptoms today?",type:"textarea",why:"Provides current context before analysis.",sensitive:true,required:true},
{code:"recent_illness",module:"safety",label:"Recent infection, fever, vaccination, or illness",type:"textarea",why:"Can temporarily change labs and wearables."},
{code:"weight_change",module:"safety",label:"Significant unplanned weight change in the last 3 months",type:"textarea",why:"Provides context for metabolic trends."},
{code:"tobacco",module:"lifestyle",label:"Tobacco or nicotine use",type:"textarea",why:"Influences cardiovascular and recovery interpretation.",sensitive:true},
{code:"alcohol",module:"lifestyle",label:"Alcohol frequency and typical amount",type:"textarea",why:"Can affect sleep, recovery, liver markers, and energy.",sensitive:true},
{code:"substances",module:"lifestyle",label:"Other regular recreational substances",type:"textarea",why:"Adds sleep, interaction, and recovery context.",sensitive:true},
{code:"current_symptoms",module:"hpi",label:"Describe the symptoms or health concerns that matter most",type:"textarea",why:"Connects subjective experience with measured data.",sensitive:true},
{code:"family_history",module:"history",label:"Important first-degree family history and approximate age of onset",type:"textarea",why:"Adds inherited and preventive context.",sensitive:true},
{code:"diet_pattern",module:"nutrition",label:"Describe a typical weekday of eating",type:"textarea",why:"Lets the plan fit your actual routine."},
{code:"cuisine_restrictions",module:"nutrition",label:"Cuisine, religious, allergy, ethical, or digestive food constraints",type:"textarea",why:"Keeps meals culturally and practically usable."},
{code:"protein_fibre",module:"nutrition",label:"Current protein, vegetables, fruit, legumes, and whole-grain pattern",type:"textarea",why:"Estimates the starting nutrition pattern."},
{code:"meal_timing",module:"nutrition",label:"Usual meal times and late-night eating pattern",type:"textarea",why:"Connects eating rhythm with sleep and metabolic signals."},
{code:"training",module:"activity",label:"Current weekly exercise and training history",type:"textarea",why:"Sets a realistic training baseline."},
{code:"injuries",module:"activity",label:"Current injuries, pain, or movement limitations",type:"textarea",why:"Keeps training selections compatible."},
{code:"equipment",module:"activity",label:"Available gym, home equipment, and preferred activities",type:"textarea",why:"Makes workouts immediately executable."},
{code:"sleep_window",module:"sleep",label:"Usual sleep and wake time on workdays and weekends",type:"text",why:"Supports circadian and recovery planning."},
{code:"shift_travel",module:"sleep",label:"Shift work, frequent travel, or irregular schedule",type:"textarea",why:"Explains timing variability."},
{code:"snoring",module:"sleep",label:"Snoring, witnessed breathing pauses, or daytime sleepiness",type:"textarea",why:"Adds important sleep-quality context.",sensitive:true},
{code:"stress",module:"mind",label:"Average stress level from 1 to 10",type:"number",why:"Shapes recovery load and habit pacing."},
{code:"phq2",module:"mind",label:"Over the last 2 weeks, how often have low mood or low interest affected you?",type:"textarea",why:"A brief wellbeing check that helps tailor support.",sensitive:true},
{code:"gad2",module:"mind",label:"Over the last 2 weeks, how often have worry or anxiety affected you?",type:"textarea",why:"A brief wellbeing check that helps tailor support.",sensitive:true},
{code:"cognition",module:"mind",label:"Any changes in focus, memory, or mental energy?",type:"textarea",why:"Adds cognitive and energy context.",sensitive:true},
{code:"environment",module:"environment",label:"Work pattern, travel, AQI, occupational, or environmental exposures",type:"textarea",why:"Captures factors outside diet and exercise."},
{code:"constraints",module:"constraints",label:"Budget, kitchen, household, schedule, or caregiving constraints",type:"textarea",why:"A useful protocol must fit real life."},
{code:"coaching_preferences",module:"coaching",label:"What coaching style and reminder cadence works best?",type:"textarea",why:"Personalizes language and follow-up."},
{code:"readiness",module:"coaching",label:"How ready are you to change one to six habits over 12 weeks?",type:"textarea",why:"Sets an achievable starting stack."},
];
