import { getDatabase, id, nowIso } from "./database";
import { labAdapterRequest, runtimeConfig } from "./integrations";
import { appendOrderEvent } from "./orders";

export async function submitOrderToLab(orderId:string,actorId:string){
  const db=await getDatabase();const order=await db.prepare("SELECT * FROM orders WHERE id=?").bind(orderId).first<Record<string,unknown>>();
  if(!order)throw new Error("Order not found");
  if(!["captured","paid"].includes(String(order.payment_status)))throw new Error("Only confirmed paid orders can be submitted");
  if(!["paid_reconciling","ops_review"].includes(String(order.status)))throw new Error("Order is already in fulfillment or is not ready for submission");
  const config=runtimeConfig();const idempotencyKey=`lab-order:${orderId}`;const existing=await db.prepare("SELECT * FROM lab_integration_events WHERE provider='lab_adapter' AND idempotency_key=?").bind(idempotencyKey).first<Record<string,unknown>>();if(existing)return existing;
  let externalReference=`sandbox-${order.reference}`;let provider="Concierge sandbox";let payload:Record<string,unknown>={orderId,memberId:order.member_id,type:order.type,productName:order.product_name,reference:order.reference,metadata:JSON.parse(String(order.metadata_json||"{}"))};
  if(config.LAB_ADAPTER_URL&&config.LAB_ADAPTER_API_KEY){const response=await labAdapterRequest("/v1/orders",{method:"POST",headers:{"Idempotency-Key":idempotencyKey},body:JSON.stringify(payload)});const result=await response.json() as Record<string,unknown>;externalReference=String(result.id??result.reference??externalReference);provider=String(result.provider??"Lab partner");payload={...payload,response:result};}
  const now=nowIso();await db.batch([db.prepare("INSERT INTO lab_integration_events (id,member_id,order_id,provider,external_reference,event_type,idempotency_key,status,payload_json,created_at,processed_at) VALUES (?,?,?,?,?,'order_submitted',?,'processed',?,?,?)").bind(id("labevent"),order.member_id,orderId,"lab_adapter",externalReference,idempotencyKey,JSON.stringify(payload),now,now),db.prepare("UPDATE orders SET vendor=?,updated_at=? WHERE id=?").bind(provider,now,orderId),db.prepare("INSERT INTO admin_events (member_id,actor_id,action,entity_type,entity_id,detail_json,created_at) VALUES (?,?,'lab.order_submitted','order',?,?,?)").bind(order.member_id,actorId,orderId,JSON.stringify({externalReference,provider}),now)]);
  await appendOrderEvent(orderId,String(order.member_id),"vendor_booked",actorId,"lab_adapter","Your test request has been placed with the laboratory partner.",JSON.stringify({externalReference,provider}));return{id:orderId,externalReference,provider,mode:config.LAB_ADAPTER_URL?"live":"sandbox"};
}

export async function processLabWebhook(eventId:string,eventType:string,payload:Record<string,unknown>){const db=await getDatabase();const externalReference=String(payload.order_id??payload.orderId??payload.reference??"");if(!externalReference)return{matched:false};const integration=await db.prepare("SELECT * FROM lab_integration_events WHERE external_reference=? ORDER BY created_at DESC LIMIT 1").bind(externalReference).first<Record<string,unknown>>();if(!integration?.order_id)return{matched:false};const statusMap:Record<string,string>={order_confirmed:"vendor_booked",appointment_scheduled:"appointment_confirmed",sample_collected:"collected",sample_received:"lab_received",processing:"processing",results_ready:"results_received",qc_failed:"qc_failed"};const status=statusMap[eventType]??"processing";const now=nowIso();await db.prepare("INSERT OR IGNORE INTO lab_integration_events (id,member_id,order_id,provider,external_reference,event_type,idempotency_key,status,payload_json,created_at,processed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id("labevent"),integration.member_id,integration.order_id,"lab_adapter",externalReference,eventType,eventId,"processed",JSON.stringify(payload),now,now).run();await appendOrderEvent(String(integration.order_id),String(integration.member_id),status,"lab_adapter","webhook",status==="results_received"?"Laboratory results have arrived and are queued for verification.":`Laboratory update: ${status.replaceAll("_"," ")}.`,JSON.stringify(payload));return{matched:true,orderId:integration.order_id,status};}
