import { getDatabase, id, nowIso, parseJson } from "./database";
import { applyResponseModel, prospectiveValidationGate, trainAndValidateResponseModel, type ModelRow, type TrainedResponseModel } from "./response-models";

async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(byte=>byte.toString(16).padStart(2,"0")).join("")}

export async function trainTargetModel(targetCode:string){const db=await getDatabase();const rows=await db.prepare(`SELECT o.member_id,o.baseline_value,o.absolute_change,o.adherence,o.quality,o.current_at,COALESCE(j.region_code,'unknown') subgroup
  FROM outcome_measurements o JOIN research_consents c ON c.member_id=o.member_id AND c.granted=1 LEFT JOIN member_jurisdictions j ON j.member_id=o.member_id WHERE o.target_code=? ORDER BY o.current_at`).bind(targetCode).all<Record<string,unknown>>();
  const modelRows:ModelRow[]=rows.results.map(row=>({features:[Number(row.baseline_value),Number(row.adherence??0),Number(row.quality)],target:Number(row.absolute_change),subgroup:String(row.subgroup),observedAt:String(row.current_at)}));
  const trained=trainAndValidateResponseModel(modelRows);const latest=await db.prepare("SELECT MAX(version) version FROM response_model_versions WHERE target_code=?").bind(targetCode).first<{version:number|null}>();const version=Number(latest?.version??0)+1;const modelId=id("model");const now=nowIso();const status=trained.eligible?"eligible_review":"collecting";const snapshotHash=await sha256(JSON.stringify(rows.results));
  await db.prepare("INSERT INTO response_model_versions (id,target_code,version,status,feature_codes_json,coefficients_json,training_window_json,metrics_json,calibration_json,subgroup_json,abstention_json,data_snapshot_hash,created_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NULL)")
    .bind(modelId,targetCode,version,status,JSON.stringify(["baseline","protocol_adherence","data_quality"]),JSON.stringify({values:trained.coefficients,ranges:trained.featureRanges}),JSON.stringify({start:rows.results[0]?.current_at??null,end:rows.results.at(-1)?.current_at??null,temporalHoldout:true}),JSON.stringify(trained.metrics),JSON.stringify(trained.calibration),JSON.stringify(trained.subgroups),JSON.stringify({gateReasons:trained.gateReasons,outOfRange:true,missingInputs:true}),snapshotHash,now).run();return{modelId,targetCode,version,status,...trained};}

export async function validateTargetModel(modelId:string,prospectiveStudyId:string,evaluatorId:string,evaluation:{n:number;mae:number;coverage:number;maxSubgroupMaeRatio:number;datasetHash:string}){if(!prospectiveStudyId.trim())throw new Error("Prospective study reference is required");if(!evaluation.datasetHash?.trim())throw new Error("Prospective dataset hash is required");const db=await getDatabase();const model=await db.prepare("SELECT * FROM response_model_versions WHERE id=?").bind(modelId).first<Record<string,unknown>>();if(!model)throw new Error("Model not found");if(model.status!=="eligible_review")throw new Error("Model has not passed the automated accuracy, calibration, and subgroup gates");const retrospective=parseJson<{mae:number}>(model.metrics_json,{mae:0});const gate=prospectiveValidationGate(evaluation,retrospective.mae);const evaluationId=id("modeleval");await db.prepare("INSERT INTO response_model_evaluations (id,model_version_id,study_id,dataset_hash,cohort_n,metrics_json,calibration_json,subgroup_json,status,evaluator_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)")
  .bind(evaluationId,modelId,prospectiveStudyId,evaluation.datasetHash,evaluation.n,JSON.stringify({mae:evaluation.mae}),JSON.stringify({coverage:evaluation.coverage}),JSON.stringify({maxMaeRatio:evaluation.maxSubgroupMaeRatio}),gate.passed?"passed":"failed",evaluatorId,nowIso()).run();if(!gate.passed)throw new Error(gate.reasons.join("; "));const window=parseJson<Record<string,unknown>>(model.training_window_json,{});await db.prepare("UPDATE response_model_versions SET status='validated',training_window_json=?,published_at=? WHERE id=?").bind(JSON.stringify({...window,prospectiveStudyId,prospectiveEvaluationId:evaluationId,validatedAt:nowIso()}),nowIso(),modelId).run();return{modelId,status:"validated",prospectiveStudyId,evaluationId};}

export async function predictForMember(memberId:string,targetCode:string){const db=await getDatabase();const[model,outcome]=await Promise.all([db.prepare("SELECT * FROM response_model_versions WHERE target_code=? AND status='validated' ORDER BY version DESC LIMIT 1").bind(targetCode).first<Record<string,unknown>>(),db.prepare("SELECT * FROM outcome_measurements WHERE member_id=? AND target_code=? ORDER BY computed_at DESC LIMIT 1").bind(memberId,targetCode).first<Record<string,unknown>>()]);let result:{status:string;reason?:string;estimate?:number;lower?:number;upper?:number;confidence?:number};let modelId="unavailable";let features:Array<number|null>=[];
  if(!model){result={status:"abstained",reason:"No prospectively validated model is available for this target"};}
  else{modelId=String(model.id);features=[outcome?Number(outcome.baseline_value):null,outcome?.adherence===null||outcome?.adherence===undefined?null:Number(outcome.adherence),outcome?Number(outcome.quality):null];const coefficients=parseJson<{values:number[];ranges:Array<{min:number;max:number}>}>(model.coefficients_json,{values:[],ranges:[]});const trained={coefficients:coefficients.values,featureRanges:coefficients.ranges,metrics:parseJson(model.metrics_json,{n:0,trainN:0,testN:0,mae:0,rmse:0,r2:0}),calibration:parseJson(model.calibration_json,{interval:.8,residualRadius:0,coverage:0}),subgroups:parseJson(model.subgroup_json,{}),eligible:true,gateReasons:[],status:String(model.status)} as TrainedResponseModel & {status:string};result=applyResponseModel(trained,features);}
  const predictionId=id("prediction");await db.prepare("INSERT INTO response_predictions (id,member_id,model_version_id,target_code,estimate,lower_bound,upper_bound,confidence,status,abstention_reason,feature_snapshot_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)")
    .bind(predictionId,memberId,modelId,targetCode,result.estimate??null,result.lower??null,result.upper??null,result.confidence??0,result.status,result.reason??null,JSON.stringify({features,codes:["baseline","protocol_adherence","data_quality"]}),nowIso()).run();return{predictionId,...result};}
