import { getDatabase, id, nowIso, parseJson } from "./database";
import { runAiDraft } from "./ai-drafting";
import { recomputeTwin } from "./twin-engine";

export async function generateReport(memberId: string, type: "biomarkers" | "wearables" | "twin" | "genetics") {
  const db = await getDatabase(); const now = nowIso();
  const snapshot = await db.prepare("SELECT * FROM twin_snapshots WHERE member_id = ? ORDER BY version DESC LIMIT 1").bind(memberId).first<Record<string, unknown>>();
  const domains = snapshot ? await db.prepare("SELECT * FROM twin_domains WHERE snapshot_id = ? ORDER BY id").bind(snapshot.id).all<Record<string, unknown>>() : { results: [] as Record<string, unknown>[] };
  const observations = await db.prepare("SELECT concept_code, domain, value_number, value_text, unit, effective_at, source, quality, metadata_json FROM observations WHERE member_id = ? ORDER BY effective_at DESC").bind(memberId).all<Record<string, unknown>>();
  const [artifacts, interpretations, crossModal] = await Promise.all([
    db.prepare("SELECT id,kind,format,genome_build,sample_id,checksum_sha256,status,qc_json,pipeline_version,created_at FROM genomic_artifacts WHERE member_id=? ORDER BY created_at DESC").bind(memberId).all<Record<string,unknown>>(),
    db.prepare("SELECT id,artifact_id,gene,rsid,category,title,summary,evidence_level,evidence_release_ids_json,limitations_json,status FROM genomic_interpretations WHERE member_id=? ORDER BY created_at DESC").bind(memberId).all<Record<string,unknown>>(),
    snapshot ? db.prepare("SELECT * FROM cross_modal_findings WHERE member_id=? AND snapshot_id=? ORDER BY id").bind(memberId,snapshot.id).all<Record<string,unknown>>() : Promise.resolve({results:[] as Record<string,unknown>[]}),
  ]);
  const sourceObservations = type === "wearables" ? observations.results.filter((row) => ["Oura", "WHOOP", "Apple Health", "Garmin", "Open Wearables"].includes(String(row.source))) : observations.results.filter((row) => !["Oura", "WHOOP", "Apple Health", "Garmin", "Open Wearables"].includes(String(row.source)));
  const decodedDomains = domains.results.map((row) => ({ code: row.domain_code, label: row.label, status: row.status, state: row.state_label, trend: row.trend, confidence: row.confidence, metric: row.key_metric, value: row.key_value, unit: row.key_unit, target: row.target, evidence: parseJson(row.evidence_json, {}) }));
  const priorities = [...decodedDomains].sort((a, b) => Number((a.evidence as { score?: number }).score ?? 70) - Number((b.evidence as { score?: number }).score ?? 70)).slice(0, 3);
  const title = type === "biomarkers" ? "Complete biomarker analysis" : type === "wearables" ? "Wearable trend analysis" : type === "genetics" ? "Genetics and inherited context" : "Biological Twin analysis";
  const geneticsReady=interpretations.results.filter((item)=>item.status!=="superseded");
  const overview = type === "genetics" ? `${geneticsReady.length} supported interpretations were prepared from ${artifacts.results.length} genomic artifact${artifacts.results.length===1?"":"s"}. Quality, build, ambiguity, and limitations remain visible in the same report.` : `${priorities.map((item) => item.label).join(", ")} are the leading priorities in this version. ${String(snapshot?.summary ?? "Data coverage is still building.")}`;
  const reportId = id("report");
  const geneticsDeep={artifacts:artifacts.results.map((row)=>({id:row.id,kind:row.kind,format:row.format,genomeBuild:row.genome_build,sampleId:row.sample_id,checksumSha256:row.checksum_sha256,status:row.status,qc:parseJson(row.qc_json,{}),pipelineVersion:row.pipeline_version,createdAt:row.created_at})),interpretations:geneticsReady.map((row)=>({id:row.id,gene:row.gene,rsid:row.rsid,category:row.category,title:row.title,summary:row.summary,evidenceLevel:row.evidence_level,evidenceReleases:parseJson(row.evidence_release_ids_json,[]),limitations:parseJson(row.limitations_json,[]),reviewState:row.status})),method:{engine:"genetics-report-v2",policyVersion:"genetics-interpretation-2026.08",rules:["Build and QC are shown before interpretation.","Common variants remain contextual and do not independently create protocol actions.","Ambiguous unphased diplotypes stay explicitly ambiguous."]}};
  const deepDive = { version: 2, generatedAt: now, snapshotId: snapshot?.id ?? null, twinVersion: snapshot?.version ?? null, overview: { priorities: type==="genetics"?geneticsReady.slice(0,5).map((item)=>({domain:item.gene,state:item.status,metric:item.rsid,target:"Context only",confidence:item.evidence_level})):priorities.map((item) => ({ domain: item.label, state: item.state, metric: `${item.metric} ${item.value} ${item.unit ?? ""}`.trim(), target: item.target, confidence: item.confidence })), reassuring: decodedDomains.filter((item) => item.status === "optimizing").map((item) => item.label), missing: decodedDomains.flatMap((item) => ((item.evidence as { missing?: string[] }).missing ?? []).map((missing) => ({ domain: item.label, missing }))) }, domains: decodedDomains, observations: type==="genetics"?[]:sourceObservations.map((row) => ({ conceptCode: row.concept_code, domain: row.domain, value: row.value_number ?? row.value_text, unit: row.unit, effectiveAt: row.effective_at, source: row.source, quality: row.quality, provenance: parseJson(row.metadata_json, {}) })), crossModal:crossModal.results.map((row)=>({id:row.id,domain:row.domain_code,title:row.title,statement:row.statement,direction:row.direction,confidence:row.confidence,layers:parseJson(row.layers_json,[]),missing:parseJson(row.missing_json,[]),methodVersion:row.method_version})), genetics:type==="genetics"?geneticsDeep:undefined, method: type==="genetics"?geneticsDeep.method:{ engine: "structured-report-v2", twinObserver: "twin-domain-observer-v1", crossModalObserver:"cross-modal-observer-v2.0.0", limitations: ["Measured laboratory values remain tied to their collection date.", "Wearable trends use personal baselines and depend on device coverage."] } };
  await db.batch([
    db.prepare("INSERT INTO reports (id, member_id, type, title, status, source_date, overview, deep_dive_json, created_at, updated_at) VALUES (?, ?, ?, ?, 'draft', ?, ?, ?, ?, ?)").bind(reportId, memberId, type, title, now.slice(0, 10), overview, JSON.stringify(deepDive), now, now),
    db.prepare("INSERT INTO approvals (id, member_id, entity_type, entity_id, role, status, reviewer_id, note, created_at, decided_at) VALUES (?, ?, 'report', ?, 'practitioner', 'pending', NULL, '', ?, NULL)").bind(id("approval"), memberId, reportId, now),
  ]);
  const refs=type==="genetics"?geneticsReady.map((item)=>String(item.id)):[...decodedDomains.map((item)=>String(item.code)),...crossModal.results.map((item)=>String(item.id))];const ai=await runAiDraft({memberId,task:type==="genetics"?"genetics_report":"cross_modal_report",entityType:"report",entityId:reportId,structuredInput:{type,overview,deepDive},inputRefs:refs,fallback:{summary:overview,priorities:[],limitations:(deepDive.method as {limitations?:string[]}).limitations??[],groundingRefs:refs.slice(0,10)}});const finalDeep={...deepDive,assistantDraft:{runId:ai.id,model:ai.model,status:ai.status,output:ai.output}};await db.prepare("UPDATE reports SET deep_dive_json=?,updated_at=? WHERE id=? AND member_id=? AND status='draft'").bind(JSON.stringify(finalDeep),nowIso(),reportId,memberId).run();
  return { id: reportId, status: "draft", title, overview, deepDive:finalDeep };
}

export async function approveReport(memberId: string, reportId: string, reviewerId: string, note: string) {
  const db = await getDatabase(); const now = nowIso();
  const report = await db.prepare("SELECT id FROM reports WHERE id = ? AND member_id = ?").bind(reportId, memberId).first(); if (!report) throw new Error("Report not found");
  await db.batch([
    db.prepare("UPDATE reports SET status = 'ready', updated_at = ? WHERE id = ? AND member_id = ?").bind(now, reportId, memberId),
    db.prepare("UPDATE approvals SET status = 'approved', reviewer_id = ?, note = ?, decided_at = ? WHERE entity_type = 'report' AND entity_id = ? AND status = 'pending'").bind(reviewerId, note, now, reportId),
    db.prepare("INSERT INTO notifications (id, member_id, channel, template, title, body, status, created_at, sent_at) VALUES (?, ?, 'in_app', 'report_ready', 'New report ready', 'Your latest analysis is ready to explore.', 'sent', ?, ?)").bind(id("notification"), memberId, now, now),
  ]);
  const released = await db.prepare("SELECT type FROM reports WHERE id=? AND member_id=?").bind(reportId,memberId).first<{type:string}>();
  if(released?.type==="genetics"){await db.prepare("UPDATE genomic_interpretations SET status='released' WHERE member_id=? AND status='draft'").bind(memberId).run();await recomputeTwin(memberId);}
  return { id: reportId, status: "ready" };
}
