import { getDatabase, id, nowIso } from "./database";
import { buildCrossModalFindings } from "./cross-modal";

type Observation = { concept_code: string; value_number: number | null; value_text: string | null; unit: string | null; effective_at: string; source: string; quality: string };
type WearDay = { day: string; sleep_minutes: number | null; sleep_score: number | null; hrv_rmssd: number | null; resting_hr: number | null; steps: number | null; workout_minutes: number | null; quality: number };
type Domain = { code: string; label: string; status: string; state: string; trend: string; confidence: number; freshness: string; metric: string; value: string; unit: string; target: string; score: number; evidence: string[]; missing: string[] };

const average = (values: Array<number | null | undefined>) => { const valid = values.filter((value): value is number => typeof value === "number" && Number.isFinite(value)); return valid.length ? valid.reduce((sum, value) => sum + value, 0) / valid.length : null; };
const percentChange = (current: number | null, previous: number | null) => current !== null && previous ? ((current - previous) / previous) * 100 : 0;
const clamp = (value: number) => Math.max(0, Math.min(100, Math.round(value)));
const confidence = (coverage: number, quality: number, freshness: number) => Number(Math.min(.98, Math.max(.2, coverage * .55 + quality * .3 + freshness * .15)).toFixed(2));

export async function recomputeTwin(memberId: string) {
  const db = await getDatabase(); const now = nowIso();
  const [observationsResult, dailyResult] = await Promise.all([
    db.prepare("SELECT concept_code, value_number, value_text, unit, effective_at, source, quality FROM observations WHERE member_id = ? ORDER BY effective_at DESC").bind(memberId).all<Observation>(),
    db.prepare("SELECT day, sleep_minutes, sleep_score, hrv_rmssd, resting_hr, steps, workout_minutes, quality FROM wearable_daily WHERE member_id = ? AND day >= date('now', '-60 day') ORDER BY day DESC").bind(memberId).all<WearDay>(),
  ]);
  const observations = new Map<string, Observation>(); for (const row of observationsResult.results) if (!observations.has(row.concept_code) && row.quality !== "rejected") observations.set(row.concept_code, row);
  const days = dailyResult.results.filter((day) => day.quality >= .7); const recent = days.slice(0, 7); const baseline = days.slice(7, 35); const validDays = days.length;
  const r7 = { sleep: average(recent.map((d) => d.sleep_minutes)), hrv: average(recent.map((d) => d.hrv_rmssd)), rhr: average(recent.map((d) => d.resting_hr)), steps: average(recent.map((d) => d.steps)), workouts: average(recent.map((d) => d.workout_minutes)) };
  const r28 = { sleep: average(baseline.map((d) => d.sleep_minutes)), hrv: average(baseline.map((d) => d.hrv_rmssd)), rhr: average(baseline.map((d) => d.resting_hr)), steps: average(baseline.map((d) => d.steps)), workouts: average(baseline.map((d) => d.workout_minutes)) };
  const lab = (code: string) => observations.get(code)?.value_number ?? null;
  const labAge = (code: string) => { const row = observations.get(code); return row ? Math.max(0, (Date.now() - new Date(row.effective_at).getTime()) / 86400000) : 999; };
  const wearableCoverage = Math.min(1, validDays / 28); const wearQuality = average(days.map((day) => day.quality)) ?? .2;
  const homa = lab("homa_ir"), insulin = lab("fasting_insulin"), glucose = lab("fasting_glucose"), apob = lab("apob"), ldl = lab("ldl"), waist = lab("waist"), creatinine = lab("creatinine"), alt = lab("alt"), ast = lab("ast");
  const metabolicScore = clamp(100 - (homa ? Math.max(0, homa - 1) * 22 : 12) - (glucose ? Math.max(0, glucose - 85) * .65 : 8) - (waist ? Math.max(0, waist - 85) * 1.2 : 5));
  const cardioScore = clamp(100 - (apob ? Math.max(0, apob - 60) * .6 : 15) - (ldl ? Math.max(0, ldl - 80) * .22 : 6));
  const sleepScore = clamp((r7.sleep ? 100 - Math.abs(465 - r7.sleep) * .22 : 45) + (average(recent.map((d) => d.sleep_score)) ?? 75) * .15 - 10);
  const recoveryDelta = percentChange(r7.hrv, r28.hrv); const recoveryScore = clamp(78 + recoveryDelta * .9 - Math.max(0, percentChange(r7.rhr, r28.rhr)) * 1.2);
  const activityScore = clamp(r7.steps ? 55 + Math.min(35, r7.steps / 260) + Math.min(10, (r7.workouts ?? 0) / 3) : 40);
  const labFresh = (code: string) => Math.max(.25, 1 - labAge(code) / 180); const labCoverage = (present: Array<number | null>) => present.filter((value) => value !== null).length / present.length;
  const trendLabel = (delta: number, inverse = false) => { const adjusted = inverse ? -delta : delta; return adjusted > 4 ? "improving" : adjusted < -4 ? "declining" : "stable"; };
  const stateFor = (score: number) => score >= 82 ? ["optimizing", "Strong"] : score >= 70 ? ["stable", "Stable"] : score >= 58 ? ["watch", "Watch"] : ["priority", "Priority"];
  const make = (domain: Omit<Domain, "status" | "state">): Domain => { const [status, state] = stateFor(domain.score); return { ...domain, status, state }; };
  const domains: Domain[] = [
    make({ code: "metabolic", label: "Metabolic", trend: "stable", confidence: confidence(labCoverage([homa, insulin, glucose, waist]), .92, labFresh("homa_ir")), freshness: labAge("homa_ir") < 90 ? "current" : "aging", metric: homa ? "HOMA-IR" : glucose ? "Fasting glucose" : "Data needed", value: String(homa ?? glucose ?? "—"), unit: homa ? "" : glucose ? "mg/dL" : "", target: homa ? "<1.5" : "Complete fasting labs", score: metabolicScore, evidence: [`HOMA-IR ${homa ?? "not measured"}`, `Fasting insulin ${insulin ?? "not measured"}`, `Waist ${waist ?? "not measured"}`], missing: [[homa, "HOMA-IR"], [glucose, "fasting glucose"], [insulin, "fasting insulin"]].filter(([v]) => v === null).map(([, n]) => String(n)) }),
    make({ code: "cardiovascular", label: "Cardiovascular", trend: "stable", confidence: confidence(labCoverage([apob, ldl]), .94, labFresh("apob")), freshness: labAge("apob") < 90 ? "current" : "aging", metric: apob ? "ApoB" : "LDL-C", value: String(apob ?? ldl ?? "—"), unit: apob || ldl ? "mg/dL" : "", target: apob ? "<80 mg/dL" : "Complete lipid panel", score: cardioScore, evidence: [`ApoB ${apob ?? "not measured"}`, `LDL-C ${ldl ?? "not measured"}`], missing: apob === null ? ["ApoB"] : [] }),
    make({ code: "sleep", label: "Sleep & circadian", trend: trendLabel(percentChange(r7.sleep, r28.sleep)), confidence: confidence(wearableCoverage, wearQuality, .98), freshness: days[0]?.day ?? "no data", metric: "7-day sleep", value: r7.sleep ? `${Math.floor(r7.sleep / 60)}h ${Math.round(r7.sleep % 60)}m` : "—", unit: "", target: "7h 30m–8h", score: sleepScore, evidence: [`${validDays} valid days`, `28-day baseline ${r28.sleep ? Math.round(r28.sleep) : "—"} min`], missing: validDays < 21 ? [`${21 - validDays} more valid days for baseline`] : [] }),
    make({ code: "recovery", label: "Autonomic recovery", trend: trendLabel(recoveryDelta), confidence: confidence(wearableCoverage, wearQuality, .98), freshness: days[0]?.day ?? "no data", metric: "HRV RMSSD", value: r7.hrv ? r7.hrv.toFixed(1) : "—", unit: "ms", target: r28.hrv ? `Personal baseline ${r28.hrv.toFixed(1)}` : "Collect baseline", score: recoveryScore, evidence: [`7-day HRV ${r7.hrv?.toFixed(1) ?? "—"} ms`, `Change ${recoveryDelta.toFixed(1)}%`, `Resting HR ${r7.rhr?.toFixed(1) ?? "—"}`], missing: validDays < 21 ? ["21 valid days required"] : [] }),
    make({ code: "activity", label: "Activity & training", trend: trendLabel(percentChange(r7.steps, r28.steps)), confidence: confidence(wearableCoverage, wearQuality, .98), freshness: days[0]?.day ?? "no data", metric: "7-day steps", value: r7.steps ? Math.round(r7.steps).toLocaleString("en-IN") : "—", unit: "steps/day", target: "8,000–10,000", score: activityScore, evidence: [`Steps ${r7.steps ? Math.round(r7.steps) : "—"}`, `Workout minutes ${r7.workouts?.toFixed(0) ?? "—"}/day`], missing: validDays < 7 ? ["7 valid activity days"] : [] }),
    make({ code: "body_composition", label: "Body composition", trend: "stable", confidence: confidence(waist ? 1 : .25, .9, labFresh("waist")), freshness: labAge("waist") < 45 ? "current" : "aging", metric: "Waist", value: String(waist ?? "—"), unit: waist ? "cm" : "", target: "Personal target", score: clamp(85 - Math.max(0, (waist ?? 90) - 85) * 2), evidence: [`Measured waist ${waist ?? "not available"}`], missing: waist === null ? ["waist measurement"] : [] }),
    make({ code: "kidney_liver", label: "Kidney & liver context", trend: "stable", confidence: confidence(labCoverage([creatinine, alt, ast]), .95, labFresh("creatinine")), freshness: labAge("creatinine") < 90 ? "current" : "aging", metric: creatinine ? "Creatinine" : alt ? "ALT" : "Safety labs", value: String(creatinine ?? alt ?? "—"), unit: creatinine ? "mg/dL" : alt ? "U/L" : "", target: "Within source range", score: clamp(88 - Math.max(0, (alt ?? 25) - 35) - Math.max(0, (ast ?? 25) - 35)), evidence: [`Creatinine ${creatinine ?? "not measured"}`, `ALT ${alt ?? "not measured"}`, `AST ${ast ?? "not measured"}`], missing: [creatinine, alt, ast].every((value) => value === null) ? ["kidney and liver panel"] : [] }),
    make({ code: "constraints", label: "Medication & constraints", trend: "stable", confidence: .62, freshness: "intake", metric: "Context coverage", value: "Active", unit: "", target: "Keep current", score: 76, evidence: ["Medication and supplement intake", "Daily-life constraints"], missing: [] }),
  ];
  const versionRow = await db.prepare("SELECT COALESCE(MAX(version), 0) AS version FROM twin_snapshots WHERE member_id = ?").bind(memberId).first<{ version: number }>(); const version = (versionRow?.version ?? 0) + 1; const snapshotId = id("twin");
  const coverage = Math.round(domains.reduce((sum, domain) => sum + domain.confidence, 0) / domains.length * 100); const priorities = [...domains].sort((a, b) => a.score - b.score).slice(0, 2); const summary = `${priorities[0].label} is the leading focus; ${priorities[1].label.toLowerCase()} is the next opportunity. ${validDays >= 21 ? "Wearable baseline is established." : `Baseline needs ${21 - validDays} more valid days.`}`;
  const statements: D1PreparedStatement[] = [db.prepare("INSERT INTO twin_snapshots (id, member_id, version, as_of, coverage, summary, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(snapshotId, memberId, version, now, coverage, summary, now)];
  for (const domain of domains) statements.push(db.prepare("INSERT INTO twin_domains (snapshot_id, member_id, domain_code, label, status, state_label, trend, confidence, freshness, key_metric, key_value, key_unit, target, evidence_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(snapshotId, memberId, domain.code, domain.label, domain.status, domain.state, domain.trend, domain.confidence, domain.freshness, domain.metric, domain.value, domain.unit, domain.target, JSON.stringify({ score: domain.score, observations: domain.evidence, missing: domain.missing, method: "twin-domain-observer-v1" })));
  await db.batch(statements); const crossModal = await buildCrossModalFindings(memberId, snapshotId); await generateDailyAdjustment(memberId, snapshotId, domains, now); return { id: snapshotId, version, coverage, summary, domains, crossModal, validDays };
}

async function generateDailyAdjustment(memberId: string, snapshotId: string, domains: Domain[], now: string) {
  const db = await getDatabase(); const protocol = await db.prepare("SELECT id FROM protocol_versions WHERE member_id = ? AND status = 'current' ORDER BY version DESC LIMIT 1").bind(memberId).first<{ id: string }>(); if (!protocol) return;
  const day = now.slice(0, 10); const recovery = domains.find((domain) => domain.code === "recovery"); const activity = domains.find((domain) => domain.code === "activity");
  let knob = "maintain", adjusted = "Follow the approved plan", rationale = "Current signals remain within the expected range.";
  if (recovery?.trend === "declining" && recovery.confidence >= .7) { knob = "training_intensity"; adjusted = "Keep Zone 2 at the lower end; skip intervals"; rationale = `Recovery is below baseline with ${Math.round(recovery.confidence * 100)}% confidence.`; }
  else if (activity?.trend === "declining" && activity.confidence >= .7) { knob = "activity_prompt"; adjusted = "Add one 12-minute post-meal walk"; rationale = "The persistent activity trend is below the personal baseline."; }
  await db.prepare("INSERT OR IGNORE INTO daily_adjustments (id, member_id, protocol_id, day, knob, previous_value, adjusted_value, rationale, twin_snapshot_id, accepted, created_at) VALUES (?, ?, ?, ?, ?, 'Approved protocol', ?, ?, ?, 1, ?)").bind(id("adjustment"), memberId, protocol.id, day, knob, adjusted, rationale, snapshotId, now).run();
}
