import { getDatabase, id, nowIso } from "./database";
import { buildCrossModalFindings } from "./cross-modal";
import { buildGenomicsPolicyView, type PhenotypeSignal } from "./genomics";

type Observation = { concept_code: string; value_number: number | null; value_text: string | null; unit: string | null; effective_at: string; source: string; quality: string };
type WearDay = { day: string; sleep_minutes: number | null; sleep_score: number | null; hrv_rmssd: number | null; resting_hr: number | null; steps: number | null; workout_minutes: number | null; quality: number };
type InheritedContext = { id: string; gene: string; rsid: string; title: string; reviewStatus: "reviewed" | "pending_review"; evidenceLabel: string; hypothesis: string; whatThisChanges: string; wouldClarify: string[]; phenotype: ReturnType<typeof buildGenomicsPolicyView>["phenotype"]; canCreateAction: false };
export type TwinDomain = { code: string; label: string; status: string; state: string; trend: string; confidence: number; freshness: string; metric: string; value: string; unit: string; target: string; score: number | null; readiness: number; evidence: string[]; missing: string[]; unknowns: string[]; change: string; nextLearningStep: string; inheritedContext: InheritedContext[] };
type DomainDraft = Omit<TwinDomain, "status" | "state" | "trend" | "confidence"> & { sufficientData: boolean; proposedTrend?: string; proposedConfidence: number; stateOverride?: string };

const average = (values: Array<number | null | undefined>) => { const valid = values.filter((value): value is number => typeof value === "number" && Number.isFinite(value)); return valid.length ? valid.reduce((sum, value) => sum + value, 0) / valid.length : null; };
const percentChange = (current: number | null, previous: number | null) => current !== null && previous !== null && previous !== 0 ? ((current - previous) / previous) * 100 : null;
const clamp = (value: number) => Math.max(0, Math.min(100, Math.round(value)));
const confidence = (coverage: number, quality: number, freshness: number) => coverage <= 0 ? 0 : Number(Math.min(.98, Math.max(0, coverage * .55 + quality * .3 + freshness * .15)).toFixed(2));
const stateFor = (score: number) => score >= 82 ? ["optimizing", "Strong"] : score >= 70 ? ["stable", "Stable"] : score >= 58 ? ["watch", "Watch"] : ["priority", "Priority"];
const trendLabel = (delta: number | null, inverse = false) => { if (delta === null) return "unknown"; const adjusted = inverse ? -delta : delta; return adjusted > 4 ? "improving" : adjusted < -4 ? "declining" : "stable"; };

export function finalizeTwinDomain(domain: DomainDraft): TwinDomain {
  if (!domain.sufficientData || domain.score === null) return { ...domain, score: null, status: "unknown", state: domain.stateOverride ?? "Data needed", trend: "unknown", confidence: Math.min(.49, Math.max(0, domain.proposedConfidence)) };
  const [status, state] = stateFor(domain.score);
  return { ...domain, status, state: domain.stateOverride ?? state, trend: domain.proposedTrend ?? "unknown", confidence: domain.proposedConfidence };
}

export function summarizeTwinDomains(domains: TwinDomain[], validWearableDays: number) {
  const measured = domains.filter((domain) => domain.score !== null);
  const learning = domains.filter((domain) => domain.score === null);
  if (!measured.length) return `Your Twin is still establishing its evidence foundation. ${learning.length} domain${learning.length === 1 ? " needs" : "s need"} more data${validWearableDays < 21 ? `; wearable baseline needs ${21 - validWearableDays} more valid days` : ""}. Inherited context can generate hypotheses, but it never creates an action by itself.`;
  const clearest = [...measured].sort((a, b) => b.confidence - a.confidence)[0];
  return `${clearest.label} currently has the clearest measured state. ${learning.length ? `${learning.length} domain${learning.length === 1 ? " remains" : "s remain"} data-limited.` : "All displayed domains meet their minimum data rules."} Genetics remains inherited context and must be corroborated by phenotype or response data.`;
}

export async function recomputeTwin(memberId: string) {
  const db = await getDatabase(); const now = nowIso();
  const [observationsResult, dailyResult, geneticsResult, intakeResult] = await Promise.all([
    db.prepare("SELECT concept_code, value_number, value_text, unit, effective_at, source, quality FROM observations WHERE member_id = ? ORDER BY effective_at DESC").bind(memberId).all<Observation>(),
    db.prepare("SELECT day, sleep_minutes, sleep_score, hrv_rmssd, resting_hr, steps, workout_minutes, quality FROM wearable_daily WHERE member_id = ? AND day >= date('now', '-60 day') ORDER BY day DESC").bind(memberId).all<WearDay>(),
    db.prepare("SELECT id,gene,rsid,title,summary,evidence_level,status,created_at FROM genomic_interpretations WHERE member_id=? ORDER BY created_at DESC").bind(memberId).all<Record<string, unknown>>(),
    db.prepare("SELECT COUNT(*) AS answered FROM intake_answers WHERE member_id=?").bind(memberId).first<{ answered: number }>(),
  ]);
  const accepted = observationsResult.results.filter((row) => row.quality !== "rejected");
  const series = new Map<string, Observation[]>(); for (const row of accepted) { const rows = series.get(row.concept_code) ?? []; rows.push(row); series.set(row.concept_code, rows); }
  const observations = new Map<string, Observation>(); for (const [code, rows] of series) observations.set(code, rows[0]);
  const days = dailyResult.results.filter((day) => day.quality >= .7); const recent = days.slice(0, 7); const baseline = days.slice(7, 35); const validDays = days.length;
  const r7 = { sleep: average(recent.map((d) => d.sleep_minutes)), hrv: average(recent.map((d) => d.hrv_rmssd)), rhr: average(recent.map((d) => d.resting_hr)), steps: average(recent.map((d) => d.steps)), workouts: average(recent.map((d) => d.workout_minutes)) };
  const r28 = { sleep: average(baseline.map((d) => d.sleep_minutes)), hrv: average(baseline.map((d) => d.hrv_rmssd)), rhr: average(baseline.map((d) => d.resting_hr)), steps: average(baseline.map((d) => d.steps)), workouts: average(baseline.map((d) => d.workout_minutes)) };
  const metricDays = (rows: WearDay[], key: keyof WearDay) => rows.filter((day) => typeof day[key] === "number").length;
  const lab = (code: string) => observations.get(code)?.value_number ?? null;
  const ageOf = (row?: Observation) => row ? Math.max(0, (Date.now() - new Date(row.effective_at).getTime()) / 86400000) : 999;
  const labAge = (codes: string[]) => Math.min(...codes.map((code) => ageOf(observations.get(code))));
  const labFresh = (codes: string[]) => Math.max(0, 1 - labAge(codes) / 180);
  const freshness = (codes: string[]) => { const rows = codes.map((code) => observations.get(code)).filter(Boolean) as Observation[]; if (!rows.length) return "no data"; const latest = [...rows].sort((a, b) => b.effective_at.localeCompare(a.effective_at))[0]; const age = ageOf(latest); return `${latest.effective_at.slice(0, 10)} · ${age <= 90 ? "current" : "aging"}`; };
  const labCoverage = (present: Array<number | null>) => present.filter((value) => value !== null).length / present.length;
  const changeFor = (code: string, label: string) => { const rows = series.get(code) ?? []; const latest = rows[0]; const previous = rows[1]; if (latest?.value_number === null || previous?.value_number === null || !latest || !previous) return `No prior ${label} result is available for a measured change.`; return `${label} changed from ${previous.value_number} to ${latest.value_number} ${latest.unit ?? ""} since ${previous.effective_at.slice(0, 10)}.`.trim(); };
  const signals: Record<string, PhenotypeSignal> = {}; for (const [code, row] of observations) if (typeof row.value_number === "number") signals[code] = { value: row.value_number, unit: row.unit, effectiveAt: row.effective_at };
  const domainGenes: Record<string, string[]> = { metabolic: ["FTO", "PPARGC1A", "MTHFR"], cardiovascular: ["APOE"], sleep: ["CYP1A2"], recovery: ["COMT", "BDNF"], activity: ["ACTN3", "PPARGC1A"], body_composition: ["FTO"], kidney_liver: [], constraints: ["CYP1A2"] };
  const inheritedFor = (code: string): InheritedContext[] => geneticsResult.results.filter((row) => (domainGenes[code] ?? []).includes(String(row.gene))).map((row) => { const policy = buildGenomicsPolicyView(row, signals); return { id: String(row.id), gene: String(row.gene), rsid: String(row.rsid), title: String(row.title), reviewStatus: row.status === "released" ? "reviewed" : "pending_review", evidenceLabel: policy.evidenceLabel, hypothesis: policy.hypothesis, whatThisChanges: policy.whatThisChanges, wouldClarify: policy.wouldClarify, phenotype: policy.phenotype, canCreateAction: false }; });
  const missing = (pairs: Array<[number | null, string]>) => pairs.filter(([value]) => value === null).map(([, label]) => label);
  const wearQuality = average(days.map((day) => day.quality)) ?? 0;
  const homa = lab("homa_ir"), insulin = lab("fasting_insulin"), glucose = lab("fasting_glucose"), apob = lab("apob"), ldl = lab("ldl"), waist = lab("waist"), creatinine = lab("creatinine"), alt = lab("alt"), ast = lab("ast");
  const metabolicReady = homa !== null && insulin !== null && glucose !== null;
  const cardioReady = apob !== null && ldl !== null;
  const sleepReady = metricDays(recent, "sleep_minutes") >= 7 && metricDays(baseline, "sleep_minutes") >= 14;
  const recoveryReady = metricDays(recent, "hrv_rmssd") >= 7 && metricDays(baseline, "hrv_rmssd") >= 14 && r7.rhr !== null && r28.rhr !== null;
  const activityReady = metricDays(recent, "steps") >= 7 && metricDays(baseline, "steps") >= 7;
  const safetyReady = creatinine !== null && alt !== null && ast !== null;
  const metabolicScore = metabolicReady ? clamp(100 - Math.max(0, homa - 1) * 22 - Math.max(0, glucose - 85) * .65) : null;
  const cardioScore = cardioReady ? clamp(100 - Math.max(0, apob - 60) * .6 - Math.max(0, ldl - 80) * .22) : null;
  const sleepScore = sleepReady && r7.sleep !== null ? clamp(100 - Math.abs(465 - r7.sleep) * .22 + (average(recent.map((d) => d.sleep_score)) ?? 0) * .1) : null;
  const recoveryDelta = percentChange(r7.hrv, r28.hrv); const rhrDelta = percentChange(r7.rhr, r28.rhr); const recoveryScore = recoveryReady && recoveryDelta !== null && rhrDelta !== null ? clamp(78 + recoveryDelta * .9 - Math.max(0, rhrDelta) * 1.2) : null;
  const activityScore = activityReady && r7.steps !== null ? clamp(55 + Math.min(35, r7.steps / 260) + Math.min(10, (r7.workouts ?? 0) / 3)) : null;
  const domains: TwinDomain[] = [
    finalizeTwinDomain({ code: "metabolic", label: "Metabolic", sufficientData: metabolicReady, proposedTrend: "unknown", proposedConfidence: confidence(labCoverage([homa, insulin, glucose]), .92, labFresh(["homa_ir", "fasting_insulin", "fasting_glucose"])), readiness: labCoverage([homa, insulin, glucose]), freshness: freshness(["homa_ir", "fasting_insulin", "fasting_glucose"]), metric: homa !== null ? "HOMA-IR" : glucose !== null ? "Fasting glucose" : "Data needed", value: String(homa ?? glucose ?? "—"), unit: homa !== null ? "" : glucose !== null ? "mg/dL" : "", target: metabolicReady ? "Personal context" : "Complete fasting metabolic set", score: metabolicScore, evidence: [[homa, "HOMA-IR"], [insulin, "Fasting insulin"], [glucose, "Fasting glucose"]].filter(([v]) => v !== null).map(([v, n]) => `${n} ${v}`), missing: missing([[homa, "HOMA-IR"], [glucose, "fasting glucose"], [insulin, "fasting insulin"]]), unknowns: metabolicReady ? [] : ["A metabolic state cannot be scored until the fasting set is complete."], change: homa !== null ? changeFor("homa_ir", "HOMA-IR") : changeFor("fasting_glucose", "fasting glucose"), nextLearningStep: "Complete or verify fasting glucose, insulin, and HOMA-IR from the same collection context.", inheritedContext: inheritedFor("metabolic") }),
    finalizeTwinDomain({ code: "cardiovascular", label: "Cardiovascular", sufficientData: cardioReady, proposedTrend: "unknown", proposedConfidence: confidence(labCoverage([apob, ldl]), .94, labFresh(["apob", "ldl"])), readiness: labCoverage([apob, ldl]), freshness: freshness(["apob", "ldl"]), metric: apob !== null ? "ApoB" : ldl !== null ? "LDL-C" : "Data needed", value: String(apob ?? ldl ?? "—"), unit: apob !== null || ldl !== null ? "mg/dL" : "", target: cardioReady ? "Personal context" : "Complete lipid context", score: cardioScore, evidence: [[apob, "ApoB"], [ldl, "LDL-C"]].filter(([v]) => v !== null).map(([v, n]) => `${n} ${v}`), missing: missing([[apob, "ApoB"], [ldl, "LDL-C"]]), unknowns: cardioReady ? [] : ["A reassuring cardiovascular score would be misleading with the current lipid coverage."], change: apob !== null ? changeFor("apob", "ApoB") : changeFor("ldl", "LDL-C"), nextLearningStep: "Add a dated ApoB and LDL-C result; inherited context can then shape what to examine, not what to prescribe.", inheritedContext: inheritedFor("cardiovascular") }),
    finalizeTwinDomain({ code: "sleep", label: "Sleep & circadian", sufficientData: sleepReady, proposedTrend: trendLabel(percentChange(r7.sleep, r28.sleep)), proposedConfidence: confidence(Math.min(1, validDays / 21), wearQuality, days.length ? .98 : 0), readiness: Math.min(1, (metricDays(recent, "sleep_minutes") + Math.min(14, metricDays(baseline, "sleep_minutes"))) / 21), freshness: days[0]?.day ?? "no data", metric: "7-day sleep", value: r7.sleep !== null ? `${Math.floor(r7.sleep / 60)}h ${Math.round(r7.sleep % 60)}m` : "—", unit: "", target: sleepReady ? "Compare with personal baseline" : "Establish 21-day baseline", score: sleepScore, evidence: r7.sleep !== null ? [`${metricDays(recent, "sleep_minutes")} recent valid nights`, `${metricDays(baseline, "sleep_minutes")} baseline nights`, `Recent average ${Math.round(r7.sleep)} min`] : [], missing: sleepReady ? [] : [`${Math.max(0, 7 - metricDays(recent, "sleep_minutes"))} recent and ${Math.max(0, 14 - metricDays(baseline, "sleep_minutes"))} baseline sleep nights remaining`], unknowns: sleepReady ? [] : ["Trend and score stay unknown until both current and baseline windows are usable."], change: r7.sleep !== null && r28.sleep !== null ? `Recent sleep is ${Math.abs(Math.round(r7.sleep - r28.sleep))} minutes ${r7.sleep >= r28.sleep ? "above" : "below"} the personal baseline.` : "No reliable personal sleep comparison is available yet.", nextLearningStep: "Keep the wearable synced through a complete current and baseline window.", inheritedContext: inheritedFor("sleep") }),
    finalizeTwinDomain({ code: "recovery", label: "Autonomic recovery", sufficientData: recoveryReady, proposedTrend: trendLabel(recoveryDelta), proposedConfidence: confidence(Math.min(1, validDays / 21), wearQuality, days.length ? .98 : 0), readiness: Math.min(1, (metricDays(recent, "hrv_rmssd") + Math.min(14, metricDays(baseline, "hrv_rmssd"))) / 21), freshness: days[0]?.day ?? "no data", metric: "HRV RMSSD", value: r7.hrv !== null ? r7.hrv.toFixed(1) : "—", unit: "ms", target: r28.hrv !== null ? `Personal baseline ${r28.hrv.toFixed(1)}` : "Collect baseline", score: recoveryScore, evidence: [r7.hrv !== null ? `Recent HRV ${r7.hrv.toFixed(1)} ms` : "", r7.rhr !== null ? `Recent resting HR ${r7.rhr.toFixed(1)}` : ""].filter(Boolean), missing: recoveryReady ? [] : ["7 recent and 14 baseline HRV days with resting-HR context"], unknowns: recoveryReady ? [] : ["Recovery is not classified from isolated or incomplete wearable readings."], change: recoveryDelta !== null ? `Recent HRV is ${Math.abs(recoveryDelta).toFixed(1)}% ${recoveryDelta >= 0 ? "above" : "below"} baseline.` : "No reliable HRV baseline comparison is available yet.", nextLearningStep: "Collect enough high-quality HRV and resting-HR nights to separate signal from day-to-day noise.", inheritedContext: inheritedFor("recovery") }),
    finalizeTwinDomain({ code: "activity", label: "Activity & training", sufficientData: activityReady, proposedTrend: trendLabel(percentChange(r7.steps, r28.steps)), proposedConfidence: confidence(Math.min(1, validDays / 14), wearQuality, days.length ? .98 : 0), readiness: Math.min(1, (metricDays(recent, "steps") + Math.min(7, metricDays(baseline, "steps"))) / 14), freshness: days[0]?.day ?? "no data", metric: "7-day steps", value: r7.steps !== null ? Math.round(r7.steps).toLocaleString("en-IN") : "—", unit: "steps/day", target: activityReady ? "Compare with personal baseline" : "Establish 14-day baseline", score: activityScore, evidence: r7.steps !== null ? [`Recent steps ${Math.round(r7.steps)}`, `Recent workout minutes ${r7.workouts?.toFixed(0) ?? "not available"}/day`] : [], missing: activityReady ? [] : ["7 recent and 7 baseline step days"], unknowns: activityReady ? [] : ["Activity is not scored until a stable personal comparison exists."], change: r7.steps !== null && r28.steps !== null ? `Recent steps are ${Math.abs(Math.round(r7.steps - r28.steps)).toLocaleString("en-IN")} ${r7.steps >= r28.steps ? "above" : "below"} baseline per day.` : "No reliable activity comparison is available yet.", nextLearningStep: "Continue syncing step and workout data through a complete comparison window.", inheritedContext: inheritedFor("activity") }),
    finalizeTwinDomain({ code: "body_composition", label: "Body composition", sufficientData: waist !== null, proposedTrend: "unknown", proposedConfidence: confidence(waist !== null ? 1 : 0, .9, labFresh(["waist"])), readiness: waist !== null ? 1 : 0, freshness: freshness(["waist"]), metric: "Waist", value: String(waist ?? "—"), unit: waist !== null ? "cm" : "", target: waist !== null ? "Track longitudinal change" : "Add measurement", score: waist !== null ? clamp(85 - Math.max(0, waist - 85) * 2) : null, evidence: waist !== null ? [`Measured waist ${waist} cm`] : [], missing: waist === null ? ["waist measurement"] : [], unknowns: waist === null ? ["No body-composition state is inferred from genetics alone."] : ["A single measurement cannot establish a trend."], change: waist !== null ? changeFor("waist", "waist") : "No longitudinal body-composition comparison is available.", nextLearningStep: waist !== null ? "Repeat the same measurement under comparable conditions." : "Add a dated waist or verified body-composition measurement.", inheritedContext: inheritedFor("body_composition") }),
    finalizeTwinDomain({ code: "kidney_liver", label: "Kidney & liver context", sufficientData: safetyReady, proposedTrend: "unknown", proposedConfidence: confidence(labCoverage([creatinine, alt, ast]), .95, labFresh(["creatinine", "alt", "ast"])), readiness: labCoverage([creatinine, alt, ast]), freshness: freshness(["creatinine", "alt", "ast"]), metric: creatinine !== null ? "Creatinine" : alt !== null ? "ALT" : "Safety labs", value: String(creatinine ?? alt ?? "—"), unit: creatinine !== null ? "mg/dL" : alt !== null ? "U/L" : "", target: safetyReady ? "Interpret against source ranges" : "Complete safety panel", score: safetyReady ? clamp(88 - Math.max(0, alt - 35) - Math.max(0, ast - 35)) : null, evidence: [[creatinine, "Creatinine"], [alt, "ALT"], [ast, "AST"]].filter(([v]) => v !== null).map(([v, n]) => `${n} ${v}`), missing: missing([[creatinine, "creatinine"], [alt, "ALT"], [ast, "AST"]]), unknowns: safetyReady ? ["Source ranges and clinical context remain necessary for interpretation."] : ["A partial safety panel is not represented by a reassuring score."], change: creatinine !== null ? changeFor("creatinine", "creatinine") : "No longitudinal safety comparison is available.", nextLearningStep: "Complete the dated kidney/liver set and retain the source reference ranges.", inheritedContext: inheritedFor("kidney_liver") }),
    finalizeTwinDomain({ code: "constraints", label: "Medication & constraints", sufficientData: false, stateOverride: Number(intakeResult?.answered ?? 0) > 0 ? "Context recorded" : "Data needed", proposedConfidence: Math.min(.49, Number(intakeResult?.answered ?? 0) / 40), readiness: Math.min(1, Number(intakeResult?.answered ?? 0) / 40), freshness: Number(intakeResult?.answered ?? 0) > 0 ? "intake" : "no data", metric: "Context coverage", value: Number(intakeResult?.answered ?? 0) > 0 ? `${Number(intakeResult?.answered ?? 0)} answers` : "—", unit: "", target: "Keep current", score: null, evidence: Number(intakeResult?.answered ?? 0) > 0 ? [`${Number(intakeResult?.answered ?? 0)} intake answers available`] : [], missing: Number(intakeResult?.answered ?? 0) > 0 ? ["Confirm medication, supplement, and practical constraints before each intervention"] : ["medications, supplements, conditions, and practical constraints"], unknowns: ["Context is shown for safety and feasibility; it is never converted into a health score."], change: "Context changes only when the member updates intake or treatment information.", nextLearningStep: "Keep medication, supplement, condition, and constraint information current.", inheritedContext: inheritedFor("constraints") }),
  ];
  const versionRow = await db.prepare("SELECT COALESCE(MAX(version), 0) AS version FROM twin_snapshots WHERE member_id = ?").bind(memberId).first<{ version: number }>(); const version = (versionRow?.version ?? 0) + 1; const snapshotId = id("twin");
  const coverage = Math.round(domains.reduce((sum, domain) => sum + domain.readiness, 0) / domains.length * 100); const summary = summarizeTwinDomains(domains, validDays);
  const statements: D1PreparedStatement[] = [db.prepare("INSERT INTO twin_snapshots (id, member_id, version, as_of, coverage, summary, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(snapshotId, memberId, version, now, coverage, summary, now)];
  for (const domain of domains) statements.push(db.prepare("INSERT INTO twin_domains (snapshot_id, member_id, domain_code, label, status, state_label, trend, confidence, freshness, key_metric, key_value, key_unit, target, evidence_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(snapshotId, memberId, domain.code, domain.label, domain.status, domain.state, domain.trend, domain.confidence, domain.freshness, domain.metric, domain.value, domain.unit, domain.target, JSON.stringify({ score: domain.score, dataState: domain.score === null ? "data_needed" : "measured", readiness: domain.readiness, observations: domain.evidence, missing: domain.missing, unknowns: domain.unknowns, change: domain.change, nextLearningStep: domain.nextLearningStep, inheritedContext: domain.inheritedContext, method: "twin-domain-observer-v2" })));
  await db.batch(statements); const crossModal = await buildCrossModalFindings(memberId, snapshotId); await generateDailyAdjustment(memberId, snapshotId, domains, now); return { id: snapshotId, version, coverage, summary, domains, crossModal, validDays };
}

async function generateDailyAdjustment(memberId: string, snapshotId: string, domains: TwinDomain[], now: string) {
  const db = await getDatabase(); const protocol = await db.prepare("SELECT id FROM protocol_versions WHERE member_id = ? AND status = 'current' ORDER BY version DESC LIMIT 1").bind(memberId).first<{ id: string }>(); if (!protocol) return;
  const day = now.slice(0, 10); const recovery = domains.find((domain) => domain.code === "recovery"); const activity = domains.find((domain) => domain.code === "activity");
  let knob = "maintain", adjusted = "Follow the approved plan", rationale = "Current measured signals do not support a bounded adjustment.";
  if (recovery?.score !== null && recovery?.trend === "declining" && recovery.confidence >= .7) { knob = "training_intensity"; adjusted = "Keep Zone 2 at the lower end; skip intervals"; rationale = `Recovery is below baseline with ${Math.round(recovery.confidence * 100)}% confidence.`; }
  else if (activity?.score !== null && activity?.trend === "declining" && activity.confidence >= .7) { knob = "activity_prompt"; adjusted = "Add one 12-minute post-meal walk"; rationale = "The measured activity trend is below the personal baseline."; }
  await db.prepare("INSERT OR IGNORE INTO daily_adjustments (id, member_id, protocol_id, day, knob, previous_value, adjusted_value, rationale, twin_snapshot_id, accepted, created_at) VALUES (?, ?, ?, ?, ?, 'Approved protocol', ?, ?, ?, 1, ?)").bind(id("adjustment"), memberId, protocol.id, day, knob, adjusted, rationale, snapshotId, now).run();
}
