import { getDatabase, id, nowIso } from "./database";
import { integrationHealth, openWearablesRequest } from "./integrations";
import { recomputeTwin } from "./twin-engine";

const supported = new Set(["oura", "whoop", "garmin"]);

async function ensureOpenWearablesUser(memberId: string, email: string, name: string) {
  const db = await getDatabase(); const existing = await db.prepare("SELECT external_user_id FROM wearable_connections WHERE member_id = ? AND provider = 'open_wearables_profile'").bind(memberId).first<{ external_user_id: string }>(); if (existing?.external_user_id) return existing.external_user_id;
  const response = await openWearablesRequest("/users", { method: "POST", body: JSON.stringify({ email, external_user_id: memberId, name }) }); const user = await response.json() as { id?: string; user_id?: string }; const externalId = user.id ?? user.user_id; if (!externalId) throw new Error("Open Wearables did not return a user ID"); const now = nowIso(); await db.prepare("INSERT INTO wearable_connections (id, member_id, provider, status, external_user_id, encrypted_token_json, scopes_json, cursor, last_sync_at, error, created_at, updated_at) VALUES (?, ?, 'open_wearables_profile', 'active', ?, NULL, '[]', NULL, NULL, NULL, ?, ?) ON CONFLICT(member_id, provider) DO UPDATE SET external_user_id=excluded.external_user_id, status='active', updated_at=excluded.updated_at").bind(id("connection"), memberId, externalId, now, now).run(); return externalId;
}

export async function connectWearable(member: { id: string; email: string; fullName: string }, provider: string, origin: string) {
  if (provider === "apple") return { mode: "native_or_import", provider, message: "Apple Health requires on-device HealthKit access. Use the Apple companion SDK when available or import the Health export now.", importUrl: "/data" };
  if (!supported.has(provider)) throw new Error("Unsupported provider"); const health = integrationHealth(); const db = await getDatabase(); const now = nowIso();
  if (health.openWearables.mode === "sandbox") { await db.prepare("INSERT INTO wearable_connections (id, member_id, provider, status, external_user_id, encrypted_token_json, scopes_json, cursor, last_sync_at, error, created_at, updated_at) VALUES (?, ?, ?, 'active', ?, NULL, ?, NULL, ?, NULL, ?, ?) ON CONFLICT(member_id, provider) DO UPDATE SET status='active', last_sync_at=excluded.last_sync_at, error=NULL, updated_at=excluded.updated_at").bind(id("connection"), member.id, provider, `sandbox-${member.id}`, JSON.stringify(["sleep", "recovery", "activity"]), now, now, now).run(); await recomputeTwin(member.id); return { mode: "sandbox", provider, connected: true, message: `${provider} sandbox connection activated with demonstration history.` }; }
  const openWearablesUserId = await ensureOpenWearablesUser(member.id, member.email, member.fullName); const redirectUri = `${origin}/data?provider=${encodeURIComponent(provider)}&connected=1`; const response = await openWearablesRequest(`/oauth/${provider}/authorize?user_id=${encodeURIComponent(openWearablesUserId)}&redirect_uri=${encodeURIComponent(redirectUri)}`); const result = await response.json() as { authorization_url?: string; state?: string }; if (!result.authorization_url) throw new Error("Authorization URL unavailable"); await db.prepare("INSERT INTO wearable_connections (id, member_id, provider, status, external_user_id, encrypted_token_json, scopes_json, cursor, last_sync_at, error, created_at, updated_at) VALUES (?, ?, ?, 'pending', ?, NULL, ?, NULL, NULL, NULL, ?, ?) ON CONFLICT(member_id, provider) DO UPDATE SET status='pending', external_user_id=excluded.external_user_id, error=NULL, updated_at=excluded.updated_at").bind(id("connection"), member.id, provider, openWearablesUserId, JSON.stringify(["sleep", "recovery", "activity"]), now, now).run(); return { mode: "open_wearables", provider, authorizationUrl: result.authorization_url };
}

export async function refreshWearableConnections(memberId: string) {
  const db = await getDatabase(); const profile = await db.prepare("SELECT external_user_id FROM wearable_connections WHERE member_id = ? AND provider = 'open_wearables_profile'").bind(memberId).first<{ external_user_id: string }>(); if (!profile?.external_user_id || integrationHealth().openWearables.mode === "sandbox") return;
  const response = await openWearablesRequest(`/users/${encodeURIComponent(profile.external_user_id)}/connections`); const connections = await response.json() as Array<{ provider: string; status: string; last_synced_at?: string; provider_user_id?: string }>; const now = nowIso(); const statements = connections.map((connection) => db.prepare("INSERT INTO wearable_connections (id, member_id, provider, status, external_user_id, encrypted_token_json, scopes_json, cursor, last_sync_at, error, created_at, updated_at) VALUES (?, ?, ?, ?, ?, NULL, '[]', NULL, ?, NULL, ?, ?) ON CONFLICT(member_id, provider) DO UPDATE SET status=excluded.status, external_user_id=excluded.external_user_id, last_sync_at=excluded.last_sync_at, error=NULL, updated_at=excluded.updated_at").bind(id("connection"), memberId, connection.provider, connection.status === "active" ? "active" : connection.status, connection.provider_user_id ?? profile.external_user_id, connection.last_synced_at ?? null, now, now)); if (statements.length) await db.batch(statements);
}

export async function syncWearable(memberId: string, provider: string) {
  const db = await getDatabase(); const connection = await db.prepare("SELECT external_user_id FROM wearable_connections WHERE member_id = ? AND provider = ?").bind(memberId, provider).first<{ external_user_id: string }>(); if (!connection) throw new Error("Connect the provider first"); const now = nowIso();
  if (integrationHealth().openWearables.mode === "sandbox") { await db.prepare("UPDATE wearable_connections SET last_sync_at = ?, status = 'active', error = NULL, updated_at = ? WHERE member_id = ? AND provider = ?").bind(now, now, memberId, provider).run(); return recomputeTwin(memberId); }
  const profile = await db.prepare("SELECT external_user_id FROM wearable_connections WHERE member_id = ? AND provider = 'open_wearables_profile'").bind(memberId).first<{ external_user_id: string }>(); const userId = profile?.external_user_id ?? connection.external_user_id;
  await openWearablesRequest(`/providers/${provider}/users/${encodeURIComponent(userId)}/sync`, { method: "POST", body: "{}" });
  const [recoveryResponse, sleepResponse, activityResponse] = await Promise.all([openWearablesRequest(`/users/${encodeURIComponent(userId)}/summaries/recovery`), openWearablesRequest(`/users/${encodeURIComponent(userId)}/summaries/sleep`), openWearablesRequest(`/users/${encodeURIComponent(userId)}/summaries/activity`)]); const [recovery, sleep, activity] = await Promise.all([recoveryResponse.json(), sleepResponse.json(), activityResponse.json()]); const metrics = extractSummaryMetrics(recovery, sleep, activity); const statements: D1PreparedStatement[] = [db.prepare("UPDATE wearable_connections SET last_sync_at = ?, status = 'active', error = NULL, updated_at = ? WHERE member_id = ? AND provider = ?").bind(now, now, memberId, provider)];
  for (const metric of metrics) statements.push(db.prepare("INSERT INTO observations (id, member_id, concept_code, domain, value_number, value_text, unit, effective_at, source, quality, metadata_json, created_at) VALUES (?, ?, ?, ?, ?, NULL, ?, ?, 'Open Wearables', 'accepted', ?, ?)").bind(id("obs"), memberId, metric.code, metric.domain, metric.value, metric.unit, now, JSON.stringify({ provider, window: metric.window, openWearablesUserId: userId }), now)); await db.batch(statements); return recomputeTwin(memberId);
}

export async function disconnectWearable(memberId: string, provider: string) { const db = await getDatabase(); const profile = await db.prepare("SELECT external_user_id FROM wearable_connections WHERE member_id = ? AND provider = 'open_wearables_profile'").bind(memberId).first<{ external_user_id: string }>(); if (profile?.external_user_id && integrationHealth().openWearables.mode === "live") await openWearablesRequest(`/users/${encodeURIComponent(profile.external_user_id)}/connections/${encodeURIComponent(provider)}`, { method: "DELETE" }); await db.prepare("UPDATE wearable_connections SET status = 'disconnected', last_sync_at = NULL, updated_at = ? WHERE member_id = ? AND provider = ?").bind(nowIso(), memberId, provider).run(); return { provider, status: "disconnected" }; }

function extractSummaryMetrics(recovery: unknown, sleep: unknown, activity: unknown) { const flat = JSON.stringify({ recovery, sleep, activity }); const get = (keys: string[]) => { for (const key of keys) { const match = new RegExp(`"${key}"\\s*:\\s*(-?\\d+(?:\\.\\d+)?)`, "i").exec(flat); if (match) return Number(match[1]); } return null; }; return [{ code: "hrv_rmssd_28d", domain: "recovery", value: get(["hrv_rmssd", "hrv", "average_hrv"]), unit: "ms", window: "summary" }, { code: "resting_hr_28d", domain: "recovery", value: get(["resting_heart_rate", "resting_hr"]), unit: "bpm", window: "summary" }, { code: "sleep_duration_28d", domain: "sleep", value: get(["sleep_duration_hours", "average_sleep_hours"]), unit: "hours", window: "summary" }, { code: "daily_steps_28d", domain: "activity", value: get(["average_steps", "steps"]), unit: "steps", window: "summary" }].filter((metric): metric is { code: string; domain: string; value: number; unit: string; window: string } => metric.value !== null); }
