import { getDatabase,id,nowIso } from "@/lib/database";
import { getMemberIdentity } from "@/lib/member";
import { requireRole } from "@/lib/authz";
import { getGenomicsState,GENOMICS_PIPELINE_VERSION } from "@/lib/genomics";

export async function GET(){const identity=await getMemberIdentity();return Response.json(await getGenomicsState(identity.id));}

export async function POST(request:Request){const actor=await requireRole(["admin","practitioner"]);const body=await request.json() as {memberId?:string;kind?:string;format?:string;genomeBuild?:string;sampleId?:string;objectKey?:string;checksumSha256?:string;size?:number;qc?:Record<string,unknown>};if(!body.memberId||!body.kind||!body.format||!body.objectKey||!body.checksumSha256)return Response.json({error:"memberId, kind, format, objectKey and checksumSha256 are required"},{status:400});if(!/^(GRCh37|GRCh38|unknown)$/.test(body.genomeBuild??"unknown"))return Response.json({error:"Unsupported genome build"},{status:400});if(!/^[a-f0-9]{64}$/i.test(body.checksumSha256))return Response.json({error:"A SHA-256 checksum is required"},{status:400});const db=await getDatabase();const artifactId=id("genome");const now=nowIso();await db.batch([db.prepare("INSERT INTO genomic_artifacts (id,member_id,upload_id,kind,format,genome_build,sample_id,object_key,checksum_sha256,size,status,qc_json,pipeline_version,created_at,updated_at) VALUES (?,?,NULL,?,?,?,?,?,?,?,'registered',?,?,?,?)").bind(artifactId,body.memberId,body.kind,body.format,body.genomeBuild??"unknown",body.sampleId??null,body.objectKey,body.checksumSha256,body.size??0,JSON.stringify(body.qc??{status:"pending",note:"Awaiting pipeline QC import"}),GENOMICS_PIPELINE_VERSION,now,now),db.prepare("INSERT INTO admin_events (member_id,actor_id,action,entity_type,entity_id,detail_json,created_at) VALUES (?,?,'genomics.artifact_registered','genomic_artifact',?,?,?)").bind(body.memberId,actor.id,artifactId,JSON.stringify({kind:body.kind,format:body.format,genomeBuild:body.genomeBuild}),now)]);return Response.json({id:artifactId,status:"registered"},{status:201});}

